Autogenerated TRANS obj
> BEGIN STRING
This is a static class
This is a static class
> END STRING

> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
null
null
> END STRING

> BEGIN STRING
"
"
> END STRING

> BEGIN STRING
AutoTranslation
AutoTranslation
> END STRING

> BEGIN STRING
en
en
> END STRING

> BEGIN STRING
https://api.cognitive.microsoft.com/sts/v1.0/issueToken
https://api.cognitive.microsoft.com/sts/v1.0/issueToken
> END STRING

> BEGIN STRING
https://api.cognitive.microsofttranslator.com/translate
https://api.cognitive.microsofttranslator.com/translate
> END STRING

> BEGIN STRING
f78dab007fdb4ad4ad5baaaa01b74829
f78dab007fdb4ad4ad5baaaa01b74829
> END STRING

> BEGIN STRING
name
name
> END STRING

> BEGIN STRING
description
description
> END STRING

> BEGIN STRING
message1
message1
> END STRING

> BEGIN STRING
message2
message2
> END STRING

> BEGIN STRING
message3
message3
> END STRING

> BEGIN STRING
message4
message4
> END STRING

> BEGIN STRING
elements
elements
> END STRING

> BEGIN STRING
equipTypes
equipTypes
> END STRING

> BEGIN STRING
skillTypes
skillTypes
> END STRING

> BEGIN STRING
weaponTypes
weaponTypes
> END STRING

> BEGIN STRING
armorTypes
armorTypes
> END STRING

> BEGIN STRING
gameTitle
gameTitle
> END STRING

> BEGIN STRING
RTK1_Option_EnJa
RTK1_Option_EnJa
> END STRING

> BEGIN STRING
Original
Original
> END STRING

> BEGIN STRING
Failed to Request for 
Failed to Request for 
> END STRING

> BEGIN STRING
%
%
> END STRING

> BEGIN STRING
 
 
> END STRING

> BEGIN STRING
POST
POST
> END STRING

> BEGIN STRING
Ocp-Apim-Subscription-Key
Ocp-Apim-Subscription-Key
> END STRING

> BEGIN STRING
api-version
api-version
> END STRING

> BEGIN STRING
3.0
3.0
> END STRING

> BEGIN STRING
to
to
> END STRING

> BEGIN STRING
Authorization
Authorization
> END STRING

> BEGIN STRING
Bearer 
Bearer 
> END STRING

> BEGIN STRING
Content-Type
Content-Type
> END STRING

> BEGIN STRING
application/json
application/json
> END STRING

> BEGIN STRING
nw.gui
nw.gui
> END STRING

> BEGIN STRING
close
close
> END STRING

> BEGIN STRING
test
test
> END STRING

> BEGIN STRING
data/Translations_%1.json
data/Translations_%1.json
> END STRING

> BEGIN STRING
GET
GET
> END STRING

> BEGIN STRING
Make Dictionary JSON file.
Make Dictionary JSON file.
> END STRING

> BEGIN STRING
Failed To Save Dictionary file. 辞書ファイルを開いている可能性があります。

> END STRING

> BEGIN STRING
fs
fs
> END STRING

> BEGIN STRING
path
path
> END STRING

> BEGIN STRING
readystatechange
readystatechange
> END STRING

> BEGIN STRING
OFF
OFF
> END STRING

> BEGIN STRING
text
text
> END STRING

> BEGIN STRING
?
?
> END STRING

> BEGIN STRING
load
load
> END STRING

> BEGIN STRING
error
error
> END STRING

> BEGIN STRING
=
=
> END STRING

> BEGIN STRING
&
&
> END STRING

> BEGIN STRING
 : 
 : 
> END STRING

> BEGIN STRING
Before Open
Before Open
> END STRING

> BEGIN STRING
Before Send [URL]
Before Send [URL]
> END STRING

> BEGIN STRING
After Send [Parameter]
After Send [Parameter]
> END STRING

> BEGIN STRING
Processing...
Processing...
> END STRING

> BEGIN STRING
Success
Success
> END STRING

> BEGIN STRING
Failure
Failure
> END STRING

> BEGIN STRING
[Code]
[Code]
> END STRING

> BEGIN STRING
xml
xml
> END STRING

> BEGIN STRING
ON
ON
> END STRING

> BEGIN STRING
TEST
TEST
> END STRING
