Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
getSkillUseCounter
getSkillUseCounter
> END STRING

> BEGIN STRING
getItemUseCounter
getItemUseCounter
> END STRING

> BEGIN STRING
getKillEnemyCounter
getKillEnemyCounter
> END STRING

> BEGIN STRING
getAllSkillUseCounter
getAllSkillUseCounter
> END STRING

> BEGIN STRING
getAllItemUseCounter
getAllItemUseCounter
> END STRING

> BEGIN STRING
getAllKillEnemyCounter
getAllKillEnemyCounter
> END STRING

> BEGIN STRING
attackDamageMax
attackDamageMax
> END STRING

> BEGIN STRING
attackDamageSum
attackDamageSum
> END STRING

> BEGIN STRING
acceptDamageMax
acceptDamageMax
> END STRING

> BEGIN STRING
acceptDamageSum
acceptDamageSum
> END STRING

> BEGIN STRING
recoverDamageSum
recoverDamageSum
> END STRING

> BEGIN STRING
payCostMpSum
payCostMpSum
> END STRING

> BEGIN STRING
payCostTpSum
payCostTpSum
> END STRING

> BEGIN STRING
deadCounter
deadCounter
> END STRING

> BEGIN STRING
item
item
> END STRING

> BEGIN STRING
weapon
weapon
> END STRING

> BEGIN STRING
armor
armor
> END STRING

> BEGIN STRING
Record
Record
> END STRING

> BEGIN STRING
Buy
Buy
> END STRING

> BEGIN STRING
Sell
Sell
> END STRING
