Autogenerated TRANS obj
> BEGIN STRING
BattleBalanceCustom
BattleBalanceCustom
> END STRING

> BEGIN STRING
Max Buff
Max Buff
> END STRING

> BEGIN STRING
Buff Rate
Buff Rate
> END STRING

> BEGIN STRING
,
,
> END STRING

> BEGIN STRING
Icon Buff Start
Icon Buff Start
> END STRING

> BEGIN STRING
32,40
32,40
> END STRING

> BEGIN STRING
Icon Debuff Start
Icon Debuff Start
> END STRING

> BEGIN STRING
48,56
48,56
> END STRING

> BEGIN STRING
Speed
Speed
> END STRING

> BEGIN STRING
Certain Hit Rate
Certain Hit Rate
> END STRING

> BEGIN STRING
Physical Hit Rate
Physical Hit Rate
> END STRING

> BEGIN STRING
Magical Hit Rate
Magical Hit Rate
> END STRING

> BEGIN STRING
Certain Eva Rate
Certain Eva Rate
> END STRING

> BEGIN STRING
Physical Eva Rate
Physical Eva Rate
> END STRING

> BEGIN STRING
Magical Eva Rate
Magical Eva Rate
> END STRING

> BEGIN STRING
Apply Critical
Apply Critical
> END STRING

> BEGIN STRING
Luk Effect Rate
Luk Effect Rate
> END STRING

> BEGIN STRING
1
1
> END STRING

> BEGIN STRING
Critical Rate
Critical Rate
> END STRING

> BEGIN STRING
Init TP
Init TP
> END STRING

> BEGIN STRING
Charge TP By Damage
Charge TP By Damage
> END STRING

> BEGIN STRING
Encounter Count
Encounter Count
> END STRING

> BEGIN STRING
Escape Ratio
Escape Ratio
> END STRING

> BEGIN STRING
0.5
0.5
> END STRING

> BEGIN STRING
Math.randomInt(
Math.randomInt(
> END STRING

> BEGIN STRING
Math.floor(
Math.floor(
> END STRING
