Autogenerated TRANS obj
> BEGIN STRING
BB_DrawGauge
BB_DrawGauge
> END STRING

> BEGIN STRING
GaugeFrameColor
GaugeFrameColor
> END STRING

> BEGIN STRING
GaugeBackColor
GaugeBackColor
> END STRING

> BEGIN STRING
GaugeHPColor1
GaugeHPColor1
> END STRING

> BEGIN STRING
GaugeHPColor2
GaugeHPColor2
> END STRING

> BEGIN STRING
GaugeMPColor1
GaugeMPColor1
> END STRING

> BEGIN STRING
GaugeMPColor2
GaugeMPColor2
> END STRING

> BEGIN STRING
GaugeTPColor1
GaugeTPColor1
> END STRING

> BEGIN STRING
GaugeTPColor2
GaugeTPColor2
> END STRING
