Autogenerated TRANS obj
> BEGIN STRING
BeforeCommon
BeforeCommon
> END STRING

> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
IndexVariableID
IndexVariableID
> END STRING

> BEGIN STRING
TargetIndexVariableID
TargetIndexVariableID
> END STRING

> BEGIN STRING
発動前コモン

> END STRING

> BEGIN STRING
turn
turn
> END STRING
