Autogenerated TRANS obj
> BEGIN STRING
Community_Basic
Community_Basic
> END STRING

> BEGIN STRING
cacheLimit
cacheLimit
> END STRING

> BEGIN STRING
screenWidth
screenWidth
> END STRING

> BEGIN STRING
screenHeight
screenHeight
> END STRING

> BEGIN STRING
renderingMode
renderingMode
> END STRING

> BEGIN STRING
alwaysDash
alwaysDash
> END STRING

> BEGIN STRING
on
on
> END STRING

> BEGIN STRING
changeWindowWidthTo
changeWindowWidthTo
> END STRING

> BEGIN STRING
changeWindowHeightTo
changeWindowHeightTo
> END STRING

> BEGIN STRING
canvas
canvas
> END STRING

> BEGIN STRING
webgl
webgl
> END STRING

> BEGIN STRING
auto
auto
> END STRING
