Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
CompareParamRefine
CompareParamRefine
> END STRING

> BEGIN STRING
AllSumOfNumber
AllSumOfNumber
> END STRING

> BEGIN STRING
Number
Number
> END STRING

> BEGIN STRING
ON
ON
> END STRING

> BEGIN STRING
最大HP除く

> END STRING

> BEGIN STRING
ExceptMapHp
ExceptMapHp
> END STRING

> BEGIN STRING
最大MP除く

> END STRING

> BEGIN STRING
ExceptMapMp
ExceptMapMp
> END STRING
