Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
CustomizeConfigItem
CustomizeConfigItem
> END STRING

> BEGIN STRING
!!!Plugin param is wrong.!!!
Plugin:
!!!Plugin param is wrong.!!!
Plugin:
> END STRING

> BEGIN STRING
.js
Name:[
.js
Name:[
> END STRING

> BEGIN STRING
]
Value:
]
Value:
> END STRING

> BEGIN STRING
TRUE
TRUE
> END STRING

> BEGIN STRING
.js
Value:
.js
Value:
> END STRING

> BEGIN STRING
NumberOptions
NumberOptions
> END STRING

> BEGIN STRING
数値項目

> END STRING

> BEGIN STRING
StringOptions
StringOptions
> END STRING

> BEGIN STRING
文字項目

> END STRING

> BEGIN STRING
SwitchOptions
SwitchOptions
> END STRING

> BEGIN STRING
スイッチ項目

> END STRING

> BEGIN STRING
VolumeOptions
VolumeOptions
> END STRING

> BEGIN STRING
音量項目

> END STRING

> BEGIN STRING
CC_UNLOCK
CC_UNLOCK
> END STRING

> BEGIN STRING
オプション任意項目の隠し解除

> END STRING

> BEGIN STRING
Number
Number
> END STRING

> BEGIN STRING
Boolean
Boolean
> END STRING

> BEGIN STRING
String
String
> END STRING

> BEGIN STRING
Volume
Volume
> END STRING

> BEGIN STRING
no item
no item
> END STRING

> BEGIN STRING
shift
shift
> END STRING
