Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
null
null
> END STRING

> BEGIN STRING
"
"
> END STRING

> BEGIN STRING
CustomizeErrorScreen
CustomizeErrorScreen
> END STRING

> BEGIN STRING
<br/\>
<br/\>
> END STRING

> BEGIN STRING
div
div
> END STRING

> BEGIN STRING
white
white
> END STRING

> BEGIN STRING
left
left
> END STRING

> BEGIN STRING
18px
18px
> END STRING

> BEGIN STRING
<hr\>
<hr\>
> END STRING

> BEGIN STRING
a
a
> END STRING

> BEGIN STRING
blue
blue
> END STRING

> BEGIN STRING
20px
20px
> END STRING

> BEGIN STRING
text-decoration
text-decoration
> END STRING

> BEGIN STRING
underline
underline
> END STRING

> BEGIN STRING
pointer
pointer
> END STRING

> BEGIN STRING
click
click
> END STRING

> BEGIN STRING
child_process
child_process
> END STRING

> BEGIN STRING
win32
win32
> END STRING

> BEGIN STRING
rundll32.exe url.dll,FileProtocolHandler "
rundll32.exe url.dll,FileProtocolHandler "
> END STRING

> BEGIN STRING
open "
open "
> END STRING

> BEGIN STRING
text
text
> END STRING

> BEGIN STRING
<br\><hr\>
<br\><hr\>
> END STRING

> BEGIN STRING
center
center
> END STRING

> BEGIN STRING
1px 1px 3px \#000
1px 1px 3px \#000
> END STRING

> BEGIN STRING
22px
22px
> END STRING
