Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
CustomizeConfigDefault
CustomizeConfigDefault
> END STRING

> BEGIN STRING
ON
ON
> END STRING

> BEGIN STRING
AlwaysDash
AlwaysDash
> END STRING

> BEGIN STRING
常時ダッシュ

> END STRING

> BEGIN STRING
CommandRemember
CommandRemember
> END STRING

> BEGIN STRING
コマンド記憶

> END STRING

> BEGIN STRING
BgmVolume
BgmVolume
> END STRING

> BEGIN STRING
BGM音量

> END STRING

> BEGIN STRING
BgsVolume
BgsVolume
> END STRING

> BEGIN STRING
BGS音量

> END STRING

> BEGIN STRING
MeVolume
MeVolume
> END STRING

> BEGIN STRING
ME音量

> END STRING

> BEGIN STRING
SeVolume
SeVolume
> END STRING

> BEGIN STRING
SE音量

> END STRING

> BEGIN STRING
EraseAlwaysDash
EraseAlwaysDash
> END STRING

> BEGIN STRING
常時ダッシュ消去

> END STRING

> BEGIN STRING
EraseCommandRemember
EraseCommandRemember
> END STRING

> BEGIN STRING
コマンド記憶消去

> END STRING

> BEGIN STRING
EraseBgmVolume
EraseBgmVolume
> END STRING

> BEGIN STRING
BGM音量消去

> END STRING

> BEGIN STRING
EraseBgsVolume
EraseBgsVolume
> END STRING

> BEGIN STRING
BGS音量消去

> END STRING

> BEGIN STRING
EraseMeVolume
EraseMeVolume
> END STRING

> BEGIN STRING
ME音量消去

> END STRING

> BEGIN STRING
EraseSeVolume
EraseSeVolume
> END STRING

> BEGIN STRING
SE音量消去

> END STRING

> BEGIN STRING
alwaysDash
alwaysDash
> END STRING

> BEGIN STRING
commandRemember
commandRemember
> END STRING

> BEGIN STRING
bgmVolume
bgmVolume
> END STRING

> BEGIN STRING
bgsVolume
bgsVolume
> END STRING

> BEGIN STRING
meVolume
meVolume
> END STRING

> BEGIN STRING
seVolume
seVolume
> END STRING
