Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
DevToolsManage
DevToolsManage
> END STRING

> BEGIN STRING
ON
ON
> END STRING

> BEGIN STRING
TRUE
TRUE
> END STRING

> BEGIN STRING
StartupDevTool
StartupDevTool
> END STRING

> BEGIN STRING
開始時に起動

> END STRING

> BEGIN STRING
FuncKeyReload
FuncKeyReload
> END STRING

> BEGIN STRING
リロードキー

> END STRING

> BEGIN STRING
FuncKeyOnTop
FuncKeyOnTop
> END STRING

> BEGIN STRING
最前面に表示キー

> END STRING

> BEGIN STRING
FuncKeyRapidGame
FuncKeyRapidGame
> END STRING

> BEGIN STRING
高速化切替キー

> END STRING

> BEGIN STRING
FuncKeyForceVictory
FuncKeyForceVictory
> END STRING

> BEGIN STRING
強制戦闘勝利キー

> END STRING

> BEGIN STRING
FuncKeyForceDefeat
FuncKeyForceDefeat
> END STRING

> BEGIN STRING
強制戦闘敗北キー

> END STRING

> BEGIN STRING
FuncKeyForceAbort
FuncKeyForceAbort
> END STRING

> BEGIN STRING
強制戦闘中断キー

> END STRING

> BEGIN STRING
FuncKeyScript
FuncKeyScript
> END STRING

> BEGIN STRING
スクリプト実行キー

> END STRING

> BEGIN STRING
FuncKeyFreeze
FuncKeyFreeze
> END STRING

> BEGIN STRING
フリーズキー

> END STRING

> BEGIN STRING
ShowFPS
ShowFPS
> END STRING

> BEGIN STRING
FPS表示

> END STRING

> BEGIN STRING
CutTitle
CutTitle
> END STRING

> BEGIN STRING
タイトルカット

> END STRING

> BEGIN STRING
RapidStart
RapidStart
> END STRING

> BEGIN STRING
高速開始

> END STRING

> BEGIN STRING
RapidSpeed
RapidSpeed
> END STRING

> BEGIN STRING
高速スピード

> END STRING

> BEGIN STRING
FakeMobile
FakeMobile
> END STRING

> BEGIN STRING
モバイル偽装

> END STRING

> BEGIN STRING
MenuBarVisible
MenuBarVisible
> END STRING

> BEGIN STRING
メニューバー表示

> END STRING

> BEGIN STRING
ClickMenu
ClickMenu
> END STRING

> BEGIN STRING
クリックメニュー

> END STRING

> BEGIN STRING
JsonSave
JsonSave
> END STRING

> BEGIN STRING
JSON形式セーブ

> END STRING

> BEGIN STRING
OutputStartupInfo
OutputStartupInfo
> END STRING

> BEGIN STRING
起動時情報出力

> END STRING

> BEGIN STRING
StartupOnTop
StartupOnTop
> END STRING

> BEGIN STRING
最前面で起動

> END STRING

> BEGIN STRING
UseReloadData
UseReloadData
> END STRING

> BEGIN STRING
リロード機能を使う

> END STRING

> BEGIN STRING
SimultaneousCtrl
SimultaneousCtrl
> END STRING

> BEGIN STRING
Ctrl同時押し

> END STRING

> BEGIN STRING
SimultaneousAlt
SimultaneousAlt
> END STRING

> BEGIN STRING
Alt同時押し

> END STRING

> BEGIN STRING
ShiftRightOnBlur
ShiftRightOnBlur
> END STRING

> BEGIN STRING
右寄せ座標

> END STRING

> BEGIN STRING
GreetingHide
GreetingHide
> END STRING

> BEGIN STRING
挨拶非表示

> END STRING

> BEGIN STRING
BirthdayMonth
BirthdayMonth
> END STRING

> BEGIN STRING
誕生月

> END STRING

> BEGIN STRING
BirthdayDate
BirthdayDate
> END STRING

> BEGIN STRING
誕生日

> END STRING

> BEGIN STRING
InvalidMessageSkip
InvalidMessageSkip
> END STRING

> BEGIN STRING
メッセージスキップ無効

> END STRING

> BEGIN STRING
FPS
FPS
> END STRING

> BEGIN STRING
MS
MS
> END STRING

> BEGIN STRING
********************************
********************************
> END STRING

> BEGIN STRING
***   User Agent             ***
***   User Agent             ***
> END STRING

> BEGIN STRING
***   Core Version           ***
***   Core Version           ***
> END STRING

> BEGIN STRING
RPG Maker Name    : 
RPG Maker Name    : 
> END STRING

> BEGIN STRING
RPG Maker Version : 
RPG Maker Version : 
> END STRING

> BEGIN STRING
RPG Maker Engine  : 
RPG Maker Engine  : 
> END STRING

> BEGIN STRING
Official Version
Official Version
> END STRING

> BEGIN STRING
***   Audio                  ***
***   Audio                  ***
> END STRING

> BEGIN STRING
Can Play OGG : 
Can Play OGG : 
> END STRING

> BEGIN STRING
Can Play M4A : 
Can Play M4A : 
> END STRING

> BEGIN STRING
***   Environment            ***
***   Environment            ***
> END STRING

> BEGIN STRING
Platform : 
Platform : 
> END STRING

> BEGIN STRING
*********************************
*********************************
> END STRING

> BEGIN STRING
***   document head           ***
***   document head           ***
> END STRING

> BEGIN STRING
***   document body           ***
***   document body           ***
> END STRING

> BEGIN STRING
test
test
> END STRING

> BEGIN STRING
 is valid only test play!
 is valid only test play!
> END STRING

> BEGIN STRING
最前面に表示

> END STRING

> BEGIN STRING
checkbox
checkbox
> END STRING

> BEGIN STRING
リロード

> END STRING

> BEGIN STRING
normal
normal
> END STRING

> BEGIN STRING
高速モード切替

> END STRING

> BEGIN STRING
戦闘強制勝利

> END STRING

> BEGIN STRING
常駐スクリプト実行

> END STRING

> BEGIN STRING
画面フリーズ

> END STRING

> BEGIN STRING
画面キャプチャ

> END STRING

> BEGIN STRING
戦闘強制敗北

> END STRING

> BEGIN STRING
戦闘強制中断

> END STRING

> BEGIN STRING
画面録画

> END STRING

> BEGIN STRING
onTop
onTop
> END STRING

> BEGIN STRING
executeDevCommand
executeDevCommand
> END STRING

> BEGIN STRING
 [!!!Rapid!!!] * 
 [!!!Rapid!!!] * 
> END STRING

> BEGIN STRING
 [!!!Slow!!!] / 
 [!!!Slow!!!] / 
> END STRING

> BEGIN STRING
 [!!!Always On Top!!!]
 [!!!Always On Top!!!]
> END STRING

> BEGIN STRING
 [!!!Freeze!!!]
 [!!!Freeze!!!]
> END STRING

> BEGIN STRING
常駐実行したいスクリプトを入力してください。

> END STRING

> BEGIN STRING
Execute Script : 
Execute Script : 
> END STRING

> BEGIN STRING
Execute Result : 
Execute Result : 
> END STRING

> BEGIN STRING
Error Script : 
Error Script : 
> END STRING

> BEGIN STRING
nw.gui
nw.gui
> END STRING

> BEGIN STRING
menubar
menubar
> END STRING

> BEGIN STRING
undefined
undefined
> END STRING

> BEGIN STRING
Database Reload
Database Reload
> END STRING

> BEGIN STRING
Map Reload
Map Reload
> END STRING

> BEGIN STRING
battleEnd
battleEnd
> END STRING

> BEGIN STRING
$dataSystem
$dataSystem
> END STRING

> BEGIN STRING
fs
fs
> END STRING

> BEGIN STRING
file%1.json
file%1.json
> END STRING

> BEGIN STRING
utf8
utf8
> END STRING

> BEGIN STRING
path
path
> END STRING

> BEGIN STRING
data/Test_
data/Test_
> END STRING

> BEGIN STRING
1_1
1_1
> END STRING

> BEGIN STRING
あけましておめでとうございます！　今年も制作がんばってください！

> END STRING

> BEGIN STRING
2_14
2_14
> END STRING

> BEGIN STRING
今日はバレンタインデーです！　素敵な贈り物はもらえましたか？？？

> END STRING

> BEGIN STRING
4_1
4_1
> END STRING

> BEGIN STRING
今日はエイプリルフールです！

> END STRING

> BEGIN STRING
8_31
8_31
> END STRING

> BEGIN STRING
夏休みも今日で終わりですね……　お仕事してる人には関係ないですが。

> END STRING

> BEGIN STRING
12_24
12_24
> END STRING

> BEGIN STRING
今日はクリスマスイブです！　こんな日まで制作するなんてえらいですね！！

> END STRING

> BEGIN STRING
12_31
12_31
> END STRING

> BEGIN STRING
今日は大晦日です。　来年も制作がんばりましょう！

> END STRING

> BEGIN STRING
"ヒラギノ明朝 ProN W3","Hiragino Mincho ProN","ＭＳ Ｐ明朝","MS PMincho"

> END STRING

> BEGIN STRING
left
left
> END STRING

> BEGIN STRING
お誕生日おめでとうございます！！！

> END STRING

> BEGIN STRING
遅くまで制作お疲れさまです……！

> END STRING

> BEGIN STRING
_
_
> END STRING

> BEGIN STRING
Script Error!! Event ID:
Script Error!! Event ID:
> END STRING

> BEGIN STRING
Script Error!! 
Script Error!! 
> END STRING

> BEGIN STRING
X:
X:
> END STRING

> BEGIN STRING
 Y:
 Y:
> END STRING

> BEGIN STRING
ID:
ID:
> END STRING

> BEGIN STRING
 Name:
 Name:
> END STRING

> BEGIN STRING
Player
Player
> END STRING

> BEGIN STRING
devToolOff
devToolOff
> END STRING

> BEGIN STRING
Ctrl+
Ctrl+
> END STRING

> BEGIN STRING
Alt+
Alt+
> END STRING

> BEGIN STRING
F
F
> END STRING

> BEGIN STRING
(
(
> END STRING

> BEGIN STRING
)
)
> END STRING

> BEGIN STRING
none
none
> END STRING

> BEGIN STRING
mousedown
mousedown
> END STRING

> BEGIN STRING
focus
focus
> END STRING

> BEGIN STRING
blur
blur
> END STRING

> BEGIN STRING
text
text
> END STRING
