Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
DP_MapZoom
DP_MapZoom
> END STRING

> BEGIN STRING
Base Scale
Base Scale
> END STRING

> BEGIN STRING
Encount Effect
Encount Effect
> END STRING

> BEGIN STRING
true
true
> END STRING

> BEGIN STRING
Camera Controll
Camera Controll
> END STRING

> BEGIN STRING
minimum
minimum
> END STRING

> BEGIN STRING
Weather Patch
Weather Patch
> END STRING

> BEGIN STRING
Picture Size Fixation
Picture Size Fixation
> END STRING

> BEGIN STRING
Old Focus
Old Focus
> END STRING

> BEGIN STRING
Easing Function
Easing Function
> END STRING

> BEGIN STRING
_scene
_scene
> END STRING

> BEGIN STRING
_spriteset
_spriteset
> END STRING

> BEGIN STRING
scale
scale
> END STRING

> BEGIN STRING
object
object
> END STRING

> BEGIN STRING
_eventId
_eventId
> END STRING

> BEGIN STRING
number
number
> END STRING

> BEGIN STRING
function
function
> END STRING

> BEGIN STRING
string
string
> END STRING

> BEGIN STRING
t
t
> END STRING

> BEGIN STRING
return 
return 
> END STRING

> BEGIN STRING
;
;
> END STRING

> BEGIN STRING
DP_MapZoom: Easing Function
DP_MapZoom: Easing Function
> END STRING

> BEGIN STRING
easing
easing
> END STRING

> BEGIN STRING
undefined
undefined
> END STRING

> BEGIN STRING
target
target
> END STRING

> BEGIN STRING
dpFocus
dpFocus
> END STRING

> BEGIN STRING
player
player
> END STRING

> BEGIN STRING
this
this
> END STRING

> BEGIN STRING
このイベント

> END STRING

> BEGIN STRING
プレイヤー

> END STRING

> BEGIN STRING
dpZoom
dpZoom
> END STRING

> BEGIN STRING
DP_Basics
DP_Basics
> END STRING

> BEGIN STRING
false
false
> END STRING

> BEGIN STRING
meta
meta
> END STRING
