Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
ERS_
ERS_
> END STRING

> BEGIN STRING
null
null
> END STRING

> BEGIN STRING
"
"
> END STRING

> BEGIN STRING
EventReSpawn
EventReSpawn
> END STRING

> BEGIN STRING


> END STRING

> BEGIN STRING
\\
\\
> END STRING

> BEGIN STRING
MAKE
MAKE
> END STRING

> BEGIN STRING
execMakeEvent
execMakeEvent
> END STRING

> BEGIN STRING
生成

> END STRING

> BEGIN STRING
MAKE_RANDOM
MAKE_RANDOM
> END STRING

> BEGIN STRING
execMakeEventRandom
execMakeEventRandom
> END STRING

> BEGIN STRING
ランダム生成

> END STRING

> BEGIN STRING
テンプレート生成

> END STRING

> BEGIN STRING
execMakeTemplateEvent
execMakeTemplateEvent
> END STRING

> BEGIN STRING
MAKE_TEMPLATE
MAKE_TEMPLATE
> END STRING

> BEGIN STRING
テンプレートランダム生成

> END STRING

> BEGIN STRING
execMakeTemplateEventRandom
execMakeTemplateEventRandom
> END STRING

> BEGIN STRING
MAKE_TEMPLATE_RANDOM
MAKE_TEMPLATE_RANDOM
> END STRING

> BEGIN STRING
最終生成イベントID取得

> END STRING

> BEGIN STRING
execGetLastSpawnEventId
execGetLastSpawnEventId
> END STRING

> BEGIN STRING
GET_LAST_SPAWN_EVENT_ID
GET_LAST_SPAWN_EVENT_ID
> END STRING

> BEGIN STRING
,
,
> END STRING

> BEGIN STRING
name
name
> END STRING

> BEGIN STRING
無効なイベントIDもしくは座標のためイベントを作成できませんでした。

> END STRING

> BEGIN STRING
座標の取得に失敗しました。

> END STRING

> BEGIN STRING
undefined
undefined
> END STRING

> BEGIN STRING
A
A
> END STRING

> BEGIN STRING
B
B
> END STRING

> BEGIN STRING
C
C
> END STRING

> BEGIN STRING
D
D
> END STRING
