Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
FastForwardCustomize
FastForwardCustomize
> END STRING

> BEGIN STRING
EventSpeedVariableId
EventSpeedVariableId
> END STRING

> BEGIN STRING
イベント速度変数

> END STRING
