Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
null
null
> END STRING

> BEGIN STRING
"
"
> END STRING

> BEGIN STRING
GeneralTrigger
GeneralTrigger
> END STRING
