Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
GraphicalDesignMode
GraphicalDesignMode
> END STRING

> BEGIN STRING
GDM
GDM
> END STRING

> BEGIN STRING
!!!このプラグインは本体バージョン1.3系以降でないと使用できません。!!!

> END STRING

> BEGIN STRING
ON
ON
> END STRING

> BEGIN STRING
TRUE
TRUE
> END STRING

> BEGIN STRING
Function
Function
> END STRING

> BEGIN STRING
$1
$1
> END STRING

> BEGIN STRING
DesignMode
DesignMode
> END STRING

> BEGIN STRING
デザインモード

> END STRING

> BEGIN STRING
ThroughWindow
ThroughWindow
> END STRING

> BEGIN STRING
ウィンドウ透過

> END STRING

> BEGIN STRING
AutoSave
AutoSave
> END STRING

> BEGIN STRING
自動保存

> END STRING

> BEGIN STRING
GridSize
GridSize
> END STRING

> BEGIN STRING
グリッドサイズ

> END STRING

> BEGIN STRING
Padding
Padding
> END STRING

> BEGIN STRING
パディング

> END STRING

> BEGIN STRING
FontSize
FontSize
> END STRING

> BEGIN STRING
フォントサイズ

> END STRING

> BEGIN STRING
LineHeight
LineHeight
> END STRING

> BEGIN STRING
行の高さ

> END STRING

> BEGIN STRING
背景透明度

> END STRING

> BEGIN STRING
MobileMake
MobileMake
> END STRING

> BEGIN STRING
モバイル版作成

> END STRING

> BEGIN STRING
FakeMobile
FakeMobile
> END STRING

> BEGIN STRING
モバイル偽装

> END STRING

> BEGIN STRING
IconSizeScale
IconSizeScale
> END STRING

> BEGIN STRING
アイコンサイズ調整

> END STRING

> BEGIN STRING
BackgroundFixed
BackgroundFixed
> END STRING

> BEGIN STRING
背景表示可否固定

> END STRING

> BEGIN STRING
RightClickHide
RightClickHide
> END STRING

> BEGIN STRING
右クリックで消去

> END STRING

> BEGIN STRING
IgnoreMesWindow
IgnoreMesWindow
> END STRING

> BEGIN STRING
メッセージウィンドウを無視

> END STRING

> BEGIN STRING
test
test
> END STRING

> BEGIN STRING
btest
btest
> END STRING

> BEGIN STRING
etest
etest
> END STRING

> BEGIN STRING
copy
copy
> END STRING

> BEGIN STRING
save
save
> END STRING

> BEGIN STRING
num
num
> END STRING

> BEGIN STRING
nw.gui
nw.gui
> END STRING

> BEGIN STRING
ok
ok
> END STRING

> BEGIN STRING
control
control
> END STRING

> BEGIN STRING
デザインモードで起動しています。 

> END STRING

> BEGIN STRING
直前に触れたオブジェクトが存在しないため、この操作は無効です。

> END STRING

> BEGIN STRING
☆☆☆ようこそ、デザインモードで起動しました。☆☆☆


> END STRING

> BEGIN STRING
デザインモードでは、オブジェクトの配置やプロパティを自由に設定して実際のゲーム画面上から画面設計できます。


> END STRING

> BEGIN STRING
--------------------操 作 方 法----------------------------------------------------------------------


> END STRING

> BEGIN STRING
ドラッグ&ドロップ ： ウィンドウや画像を掴んで好きな場所に再配置します。


> END STRING

> BEGIN STRING
Ctrl+マウス ： ウィンドウや画像がグリッドにスナップします。(Macの場合はoptionキー)


> END STRING

> BEGIN STRING
Shift+マウス ： ウィンドウや画像がオブジェクトや画面端にスナップしなくなります。


> END STRING

> BEGIN STRING
コンソールに「changePos(x, y);」(x:X座標、y:Y座標)と打ち込むと直前に編集したウィンドウ位置を変更できます。


> END STRING

> BEGIN STRING
Ctrl+S ： 全ての変更を保存します。


> END STRING

> BEGIN STRING
Ctrl+C ： 直前に操作した座標をクリップボードにコピーします。


> END STRING

> BEGIN STRING
Ctrl+Z ： 直前に行った操作を元に戻します。


> END STRING

> BEGIN STRING
Ctrl+Shift+Enter ： 表示している画面の配置を全てリセットしてロードし直します。


> END STRING

> BEGIN STRING
右クリック ： ウィンドウの枠（もしくはウィンドウ全体）の表示/非表示を切り替えます。


> END STRING

> BEGIN STRING
数字キー ： ウィンドウの範囲内で押下すると、以下のとおり対応するプロパティを変更できます。


> END STRING

> BEGIN STRING
 1. ウィンドウの横幅(※1)


> END STRING

> BEGIN STRING
 2. ウィンドウの高さ(直接指定)(※1)


> END STRING

> BEGIN STRING
 3. ウィンドウの余白(※2)


> END STRING

> BEGIN STRING
 4. ウィンドウのフォントサイズ(※2)


> END STRING

> BEGIN STRING
 5. ウィンドウの1行のあたりの高さ(※2)


> END STRING

> BEGIN STRING
 6. ウィンドウの背景透明度(※2)


> END STRING

> BEGIN STRING
 7. ウィンドウの行数(※2)


> END STRING

> BEGIN STRING
 8. ウィンドウの背景画像ファイル名


> END STRING

> BEGIN STRING
 9. ウィンドウのフォント名(※3)


> END STRING

> BEGIN STRING
※1 JS計算式を適用できます。計算式は入力したその場で1回だけ評価されます。


> END STRING

> BEGIN STRING
※2 JS計算式を適用できます。計算式は保存され、画面表示のたびに再評価されます。


> END STRING

> BEGIN STRING
分からない場合、今まで通り数値を設定すれば問題ありません。


> END STRING

> BEGIN STRING
※3 あらかじめフォントをロードする必要があります。「フォントロードプラグイン」をお使いください。


> END STRING

> BEGIN STRING
入手先：raw.githubusercontent.com/triacontane/RPGMakerMV/master/FontLoad.js


> END STRING

> BEGIN STRING
※4 Macの場合、Ctrlキーはoptionキーで代用してください。（commandキーでは反応しません）


> END STRING

> BEGIN STRING
-----------------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------------------
> END STRING

> BEGIN STRING
以下の操作ログが表示されます。


> END STRING

> BEGIN STRING
X座標[

> END STRING

> BEGIN STRING
]をクリップボードにコピーしました。

> END STRING

> BEGIN STRING
Y座標[

> END STRING

> BEGIN STRING
text
text
> END STRING

> BEGIN STRING
すべての変更を保存しました。

> END STRING

> BEGIN STRING
左記の番号の操作を元に戻しました。

> END STRING

> BEGIN STRING
shift
shift
> END STRING

> BEGIN STRING
 
 
> END STRING

> BEGIN STRING
 : 
 : 
> END STRING

> BEGIN STRING
自動保存により変更が保存されました。

> END STRING

> BEGIN STRING
fs
fs
> END STRING

> BEGIN STRING
path
path
> END STRING

> BEGIN STRING
data/
data/
> END STRING

> BEGIN STRING
rgba(255,255,255,1.0)
rgba(255,255,255,1.0)
> END STRING

> BEGIN STRING
X:[
X:[
> END STRING

> BEGIN STRING
] Y:[
] Y:[
> END STRING

> BEGIN STRING
]
]
> END STRING

> BEGIN STRING
位置を変更しました。

> END STRING

> BEGIN STRING
背景の表示/非表示を変更しました。

> END STRING

> BEGIN STRING
の値を

> END STRING

> BEGIN STRING
に変更しました。

> END STRING

> BEGIN STRING
num1
num1
> END STRING

> BEGIN STRING
横幅

> END STRING

> BEGIN STRING
width
width
> END STRING

> BEGIN STRING
num2
num2
> END STRING

> BEGIN STRING
高さ

> END STRING

> BEGIN STRING
height
height
> END STRING

> BEGIN STRING
num3
num3
> END STRING

> BEGIN STRING
_customPadding
_customPadding
> END STRING

> BEGIN STRING
num4
num4
> END STRING

> BEGIN STRING
_customFontSize
_customFontSize
> END STRING

> BEGIN STRING
num5
num5
> END STRING

> BEGIN STRING
_customLineHeight
_customLineHeight
> END STRING

> BEGIN STRING
num6
num6
> END STRING

> BEGIN STRING
背景の透明度

> END STRING

> BEGIN STRING
_customBackOpacity
_customBackOpacity
> END STRING

> BEGIN STRING
num7
num7
> END STRING

> BEGIN STRING
行数

> END STRING

> BEGIN STRING
_customLineNumber
_customLineNumber
> END STRING

> BEGIN STRING
num8
num8
> END STRING

> BEGIN STRING
背景画像のファイル名

> END STRING

> BEGIN STRING
_customBackFileName
_customBackFileName
> END STRING

> BEGIN STRING
num9
num9
> END STRING

> BEGIN STRING
フォント名

> END STRING

> BEGIN STRING
_customFontFace
_customFontFace
> END STRING

> BEGIN STRING
を入力してください。

> END STRING

> BEGIN STRING
endX
endX
> END STRING

> BEGIN STRING
endY
endY
> END STRING

> BEGIN STRING
^
^
> END STRING

> BEGIN STRING
解除_メッセージウィンドウ

> END STRING

> BEGIN STRING
_UNLOCK_MESSAGE_WINDOW
_UNLOCK_MESSAGE_WINDOW
> END STRING

> BEGIN STRING
固定_メッセージウィンドウ

> END STRING

> BEGIN STRING
_LOCK_MESSAGE_WINDOW
_LOCK_MESSAGE_WINDOW
> END STRING

> BEGIN STRING
解除_選択肢ウィンドウ

> END STRING

> BEGIN STRING
_UNLOCK_CHOICE_WINDOW
_UNLOCK_CHOICE_WINDOW
> END STRING

> BEGIN STRING
固定_選択肢ウィンドウ

> END STRING

> BEGIN STRING
_LOCK_CHOICE_WINDOW
_LOCK_CHOICE_WINDOW
> END STRING

> BEGIN STRING
$dataContainerProperties
$dataContainerProperties
> END STRING

> BEGIN STRING
ContainerProperties.json
ContainerProperties.json
> END STRING

> BEGIN STRING
ContainerPropertiesMobile.json
ContainerPropertiesMobile.json
> END STRING

> BEGIN STRING
が見付かりませんでした。

> END STRING

> BEGIN STRING
GET
GET
> END STRING

> BEGIN STRING
application/json
application/json
> END STRING

> BEGIN STRING
x
x
> END STRING

> BEGIN STRING
y
y
> END STRING

> BEGIN STRING
ファイルが見付からなかったので、左記の番号の変更を戻しました。

> END STRING

> BEGIN STRING
IconSet
IconSet
> END STRING

> BEGIN STRING
left
left
> END STRING

> BEGIN STRING
center
center
> END STRING

> BEGIN STRING
1
1
> END STRING

> BEGIN STRING
right
right
> END STRING

> BEGIN STRING
2
2
> END STRING
