Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
HalfMove
HalfMove
> END STRING

> BEGIN STRING
HM
HM
> END STRING

> BEGIN STRING
ON
ON
> END STRING

> BEGIN STRING
TRUE
TRUE
> END STRING

> BEGIN STRING
,
,
> END STRING

> BEGIN STRING
Direction8Move
Direction8Move
> END STRING

> BEGIN STRING
8方向移動

> END STRING

> BEGIN STRING
EventThrough
EventThrough
> END STRING

> BEGIN STRING
イベントすり抜け

> END STRING

> BEGIN STRING
DisableForcing
DisableForcing
> END STRING

> BEGIN STRING
強制中無効

> END STRING

> BEGIN STRING
AvoidCorner
AvoidCorner
> END STRING

> BEGIN STRING
角回避

> END STRING

> BEGIN STRING
DiagonalSlow
DiagonalSlow
> END STRING

> BEGIN STRING
斜め移動中減速

> END STRING

> BEGIN STRING
TriggerExpansion
TriggerExpansion
> END STRING

> BEGIN STRING
トリガー拡大

> END STRING

> BEGIN STRING
AdjustmentRealStep
AdjustmentRealStep
> END STRING

> BEGIN STRING
実歩数調整

> END STRING

> BEGIN STRING
UpperNpTerrainTag
UpperNpTerrainTag
> END STRING

> BEGIN STRING
上半分移動不可地形

> END STRING

> BEGIN STRING
UpperNpRegionId
UpperNpRegionId
> END STRING

> BEGIN STRING
上半分移動不可Region

> END STRING

> BEGIN STRING
LowerNpTerrainTag
LowerNpTerrainTag
> END STRING

> BEGIN STRING
下半分移動不可地形

> END STRING

> BEGIN STRING
LowerNpRegionId
LowerNpRegionId
> END STRING

> BEGIN STRING
下半分移動不可Region

> END STRING

> BEGIN STRING
RightNpTerrainTag
RightNpTerrainTag
> END STRING

> BEGIN STRING
右半分移動不可地形

> END STRING

> BEGIN STRING
RightNpRegionId
RightNpRegionId
> END STRING

> BEGIN STRING
右半分移動不可Region

> END STRING

> BEGIN STRING
LeftNpTerrainTag
LeftNpTerrainTag
> END STRING

> BEGIN STRING
左半分移動不可地形

> END STRING

> BEGIN STRING
LeftNpRegionId
LeftNpRegionId
> END STRING

> BEGIN STRING
左半分移動不可Region

> END STRING

> BEGIN STRING
AllNpTerrainTag
AllNpTerrainTag
> END STRING

> BEGIN STRING
全方向移動不可地形

> END STRING

> BEGIN STRING
AllNpRegionId
AllNpRegionId
> END STRING

> BEGIN STRING
全方向移動不可Region

> END STRING

> BEGIN STRING
MultiStartDisable
MultiStartDisable
> END STRING

> BEGIN STRING
イベント複数起動防止

> END STRING

> BEGIN STRING
EventOverlap
EventOverlap
> END STRING

> BEGIN STRING
イベント位置重複OK

> END STRING

> BEGIN STRING
8MoveSwitch
8MoveSwitch
> END STRING

> BEGIN STRING
8方向移動スイッチ

> END STRING

> BEGIN STRING
半歩移動禁止

> END STRING

> BEGIN STRING
HALF_MOVE_DISABLE
HALF_MOVE_DISABLE
> END STRING

> BEGIN STRING
半歩移動許可

> END STRING

> BEGIN STRING
HALF_MOVE_ENABLE
HALF_MOVE_ENABLE
> END STRING

> BEGIN STRING
_halfDisable
_halfDisable
> END STRING

> BEGIN STRING
HalfDisable
HalfDisable
> END STRING

> BEGIN STRING
半歩禁止

> END STRING

> BEGIN STRING
ThroughDisable
ThroughDisable
> END STRING

> BEGIN STRING
すり抜け禁止

> END STRING

> BEGIN STRING
Width
Width
> END STRING

> BEGIN STRING
横幅

> END STRING

> BEGIN STRING
Height
Height
> END STRING

> BEGIN STRING
高さ

> END STRING

> BEGIN STRING
8MoveDisable
8MoveDisable
> END STRING

> BEGIN STRING
8方向移動禁止

> END STRING

> BEGIN STRING
ExpansionArea
ExpansionArea
> END STRING

> BEGIN STRING
拡大領域

> END STRING

> BEGIN STRING
function
function
> END STRING
