Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
HorizontalScrollingMove
HorizontalScrollingMove
> END STRING

> BEGIN STRING
TRUE
TRUE
> END STRING

> BEGIN STRING
ValidSwitchId
ValidSwitchId
> END STRING

> BEGIN STRING
有効スイッチ番号

> END STRING

> BEGIN STRING
ValidUpPlayer
ValidUpPlayer
> END STRING

> BEGIN STRING
プレイヤー上向き許容

> END STRING

> BEGIN STRING
ValidUpEvent
ValidUpEvent
> END STRING

> BEGIN STRING
イベント上向き許容

> END STRING

> BEGIN STRING
ImageOnly
ImageOnly
> END STRING

> BEGIN STRING
画像のみ向き制限

> END STRING
