Autogenerated TRANS obj
> BEGIN STRING
ItemBook
ItemBook
> END STRING

> BEGIN STRING
Unknown Data
Unknown Data
> END STRING

> BEGIN STRING
??????
??????
> END STRING

> BEGIN STRING
Price Text
Price Text
> END STRING

> BEGIN STRING
Price
Price
> END STRING

> BEGIN STRING
Equip Text
Equip Text
> END STRING

> BEGIN STRING
Equip
Equip
> END STRING

> BEGIN STRING
Type Text
Type Text
> END STRING

> BEGIN STRING
Type
Type
> END STRING

> BEGIN STRING
open
open
> END STRING

> BEGIN STRING
add
add
> END STRING

> BEGIN STRING
remove
remove
> END STRING

> BEGIN STRING
complete
complete
> END STRING

> BEGIN STRING
clear
clear
> END STRING

> BEGIN STRING
item
item
> END STRING

> BEGIN STRING
weapon
weapon
> END STRING

> BEGIN STRING
armor
armor
> END STRING

> BEGIN STRING
cancel
cancel
> END STRING

> BEGIN STRING
no
no
> END STRING

> BEGIN STRING
-
-
> END STRING

> BEGIN STRING
right
right
> END STRING
