Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
LoadingExtend
LoadingExtend
> END STRING

> BEGIN STRING
ON
ON
> END STRING

> BEGIN STRING
ImageColumn
ImageColumn
> END STRING

> BEGIN STRING
イメージ列数

> END STRING

> BEGIN STRING
ImageRow
ImageRow
> END STRING

> BEGIN STRING
イメージ行数

> END STRING

> BEGIN STRING
ShowingType
ShowingType
> END STRING

> BEGIN STRING
表示タイプ

> END STRING

> BEGIN STRING
AnimationInterval
AnimationInterval
> END STRING

> BEGIN STRING
アニメーション間隔

> END STRING

> BEGIN STRING
XPosition
XPosition
> END STRING

> BEGIN STRING
表示位置X座標

> END STRING

> BEGIN STRING
YPosition
YPosition
> END STRING

> BEGIN STRING
表示位置Y座標

> END STRING

> BEGIN STRING
WaitingFrames
WaitingFrames
> END STRING

> BEGIN STRING
待機フレーム数

> END STRING

> BEGIN STRING
NoFlashing
NoFlashing
> END STRING

> BEGIN STRING
点滅なし

> END STRING

> BEGIN STRING
2d
2d
> END STRING
