Autogenerated TRANS obj
> BEGIN STRING
MadeWithMv
MadeWithMv
> END STRING

> BEGIN STRING
Show Made With MV
Show Made With MV
> END STRING

> BEGIN STRING
Made with MV Image
Made with MV Image
> END STRING

> BEGIN STRING
Show Custom Splash
Show Custom Splash
> END STRING

> BEGIN STRING
Custom Image
Custom Image
> END STRING

> BEGIN STRING
Fade Out Time
Fade Out Time
> END STRING

> BEGIN STRING
Fade In Time
Fade In Time
> END STRING

> BEGIN STRING
Wait Time
Wait Time
> END STRING

> BEGIN STRING
Player's starting position is not set
Player's starting position is not set
> END STRING
