Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
MasterVolumeOption
MasterVolumeOption
> END STRING

> BEGIN STRING
ItemName
ItemName
> END STRING

> BEGIN STRING
項目名称

> END STRING

> BEGIN STRING
DefaultValue
DefaultValue
> END STRING

> BEGIN STRING
初期値

> END STRING

> BEGIN STRING
OffsetValue
OffsetValue
> END STRING

> BEGIN STRING
音量の増減量

> END STRING

> BEGIN STRING
masterVolume
masterVolume
> END STRING
