Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
MenuCommonEvent
MenuCommonEvent
> END STRING

> BEGIN STRING
TRUE
TRUE
> END STRING

> BEGIN STRING
!!!Plugin param is wrong.!!!
Plugin:.js
Name:[]
Value:
!!!Plugin param is wrong.!!!
Plugin:.js
Name:[]
Value:
> END STRING

> BEGIN STRING
$1
$1
> END STRING

> BEGIN STRING
CommonEventInfo
CommonEventInfo
> END STRING

> BEGIN STRING
コモンイベント情報

> END STRING

> BEGIN STRING
CommandPrefix
CommandPrefix
> END STRING

> BEGIN STRING
コマンド接頭辞

> END STRING

> BEGIN STRING
MaxMenuPicture
MaxMenuPicture
> END STRING

> BEGIN STRING
ピクチャ表示最大数

> END STRING

> BEGIN STRING
SaveInterpreterIndex
SaveInterpreterIndex
> END STRING

> BEGIN STRING
実行位置を記憶

> END STRING

> BEGIN STRING
ActivateTimer
ActivateTimer
> END STRING

> BEGIN STRING
タイマー有効化

> END STRING

> BEGIN STRING
ウィンドウ操作禁止

> END STRING

> BEGIN STRING
execDisableWindowControl
execDisableWindowControl
> END STRING

> BEGIN STRING
DISABLE_WINDOW_CONTROL
DISABLE_WINDOW_CONTROL
> END STRING

> BEGIN STRING
ウィンドウ操作許可

> END STRING

> BEGIN STRING
execEnableWindowControl
execEnableWindowControl
> END STRING

> BEGIN STRING
ENABLE_WINDOW_CONTROL
ENABLE_WINDOW_CONTROL
> END STRING

> BEGIN STRING
イベントの実行停止

> END STRING

> BEGIN STRING
execStopEvent
execStopEvent
> END STRING

> BEGIN STRING
STOP_EVENT
STOP_EVENT
> END STRING

> BEGIN STRING
_
_
> END STRING

> BEGIN STRING
glossaryWindow
glossaryWindow
> END STRING

> BEGIN STRING
glossaryListWindow
glossaryListWindow
> END STRING

> BEGIN STRING
CommonEventId
CommonEventId
> END STRING

> BEGIN STRING
SceneName
SceneName
> END STRING
