Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
null
null
> END STRING

> BEGIN STRING
"
"
> END STRING

> BEGIN STRING
MessageWindowHidden
MessageWindowHidden
> END STRING

> BEGIN STRING
undefined
undefined
> END STRING

> BEGIN STRING
右クリック

> END STRING

> BEGIN STRING
light_click
light_click
> END STRING

> BEGIN STRING
ok
ok
> END STRING
