Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
MessageSpeedCustomize
MessageSpeedCustomize
> END STRING

> BEGIN STRING
VariableSpeed
VariableSpeed
> END STRING

> BEGIN STRING
表示速度変数

> END STRING

> BEGIN STRING
RapidShowSwitch
RapidShowSwitch
> END STRING

> BEGIN STRING
瞬間表示スイッチ

> END STRING

> BEGIN STRING
\>
\>
> END STRING

> BEGIN STRING
MS
MS
> END STRING
