Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
MessageSkip
MessageSkip
> END STRING

> BEGIN STRING
ON
ON
> END STRING

> BEGIN STRING
TRUE
TRUE
> END STRING

> BEGIN STRING
f
f
> END STRING

> BEGIN STRING
SkipKey
SkipKey
> END STRING

> BEGIN STRING
スキップキー

> END STRING

> BEGIN STRING
AutoKey
AutoKey
> END STRING

> BEGIN STRING
オートキー

> END STRING

> BEGIN STRING
messageSkip
messageSkip
> END STRING

> BEGIN STRING
messageAuto
messageAuto
> END STRING

> BEGIN STRING
SkipPicture
SkipPicture
> END STRING

> BEGIN STRING
スキップピクチャ

> END STRING

> BEGIN STRING
SkipPictureX
SkipPictureX
> END STRING

> BEGIN STRING
スキップピクチャX

> END STRING

> BEGIN STRING
SkipPictureY
SkipPictureY
> END STRING

> BEGIN STRING
スキップピクチャY

> END STRING

> BEGIN STRING
AutoPicture
AutoPicture
> END STRING

> BEGIN STRING
オートピクチャ

> END STRING

> BEGIN STRING
AutoPictureX
AutoPictureX
> END STRING

> BEGIN STRING
オートピクチャX

> END STRING

> BEGIN STRING
AutoPictureY
AutoPictureY
> END STRING

> BEGIN STRING
オートピクチャY

> END STRING

> BEGIN STRING
PictureAnchor
PictureAnchor
> END STRING

> BEGIN STRING
ボタン原点

> END STRING

> BEGIN STRING
PictureSwitchId
PictureSwitchId
> END STRING

> BEGIN STRING
ボタン表示スイッチID

> END STRING

> BEGIN STRING
PressingSkip
PressingSkip
> END STRING

> BEGIN STRING
押し続けスキップ

> END STRING

> BEGIN STRING
SkipSwitchId
SkipSwitchId
> END STRING

> BEGIN STRING
スキップスイッチ

> END STRING

> BEGIN STRING
AutoSwitchIId
AutoSwitchIId
> END STRING

> BEGIN STRING
オートスイッチ

> END STRING

> BEGIN STRING
InvalidSwitchId
InvalidSwitchId
> END STRING

> BEGIN STRING
無効化スイッチ

> END STRING

> BEGIN STRING
ResetOnEndSwitch
ResetOnEndSwitch
> END STRING

> BEGIN STRING
終了解除スイッチID

> END STRING

> BEGIN STRING
IconSet
IconSet
> END STRING

> BEGIN STRING


> END STRING

> BEGIN STRING
!
!
> END STRING

> BEGIN STRING
AutoWaitFrame
AutoWaitFrame
> END STRING

> BEGIN STRING
オート待機フレーム

> END STRING

> BEGIN STRING
SkipIcon
SkipIcon
> END STRING

> BEGIN STRING
スキップアイコン

> END STRING

> BEGIN STRING
AutoIcon
AutoIcon
> END STRING

> BEGIN STRING
オートアイコン

> END STRING

> BEGIN STRING
SkipAlreadyReadMessage
SkipAlreadyReadMessage
> END STRING
