Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING


> END STRING

> BEGIN STRING
\\
\\
> END STRING

> BEGIN STRING
getVarAsBool(param)の引数に、配列を渡しています。a[i]などを忘れている可能性が高いです。  falseを返します。

> END STRING

> BEGIN STRING
ON
ON
> END STRING

> BEGIN STRING
TRUE
TRUE
> END STRING

> BEGIN STRING
1
1
> END STRING

> BEGIN STRING
getVarAsNumber(param)の引数に、配列を渡しています。a[i]などを忘れている可能性が高いです。  0を返します。

> END STRING

> BEGIN STRING
getVarAsString(param)の引数に、配列を渡しています。a[i]などを忘れている可能性が高いです。  ブランク””を返します。

> END STRING

> BEGIN STRING
OFF
OFF
> END STRING

> BEGIN STRING
bool
bool
> END STRING

> BEGIN STRING
CheckParam (type, param, def)の引数paramに、配列を渡しています。a[i]などを忘れている可能性が高いです。  falseを返します。

> END STRING

> BEGIN STRING
num
num
> END STRING

> BEGIN STRING
CheckParam (type, param, def)の引数paramに、配列を渡しています。a[i]などを忘れている可能性が高いです。  0を返します。

> END STRING

> BEGIN STRING
■■■このプラグインを無効にします。■■■.詳細はデバッグ出力を見てください

> END STRING

> BEGIN STRING
指定した値[

> END STRING

> BEGIN STRING
]が数値ではありません。
■■■このプラグインを無効にします■■■。

> END STRING

> BEGIN STRING
parseIntStrict: プラグインのパラメータ「

> END STRING

> BEGIN STRING
」に指定した値: 

> END STRING

> BEGIN STRING
 を数値

> END STRING

> BEGIN STRING
～

> END STRING

> BEGIN STRING
に抑える過程で発生したエラーです。

> END STRING

> BEGIN STRING
,
,
> END STRING

> BEGIN STRING
 
 
> END STRING

> BEGIN STRING
test
test
> END STRING

> BEGIN STRING
minRPG_CustomizeGameSpeed
minRPG_CustomizeGameSpeed
> END STRING

> BEGIN STRING
isDebugOut
isDebugOut
> END STRING

> BEGIN STRING
デバッグ出力するか

> END STRING

> BEGIN STRING
isNoChangeSpeed_inThisPlugin
isNoChangeSpeed_inThisPlugin
> END STRING

> BEGIN STRING
【機能】スピード変更

> END STRING

> BEGIN STRING
isNoChangeParamLimit_inThisPlugin
isNoChangeParamLimit_inThisPlugin
> END STRING

> BEGIN STRING
【機能】ステータス限界値変更

> END STRING

> BEGIN STRING
isOnControlBattleEncountAndWinLose
isOnControlBattleEncountAndWinLose
> END STRING

> BEGIN STRING
【機能】戦闘を検知するか

> END STRING

> BEGIN STRING
isChangeDefault_Migawari
isChangeDefault_Migawari
> END STRING

> BEGIN STRING
【機能】身代わり条件を変えるか

> END STRING

> BEGIN STRING
MAPSPEED_DEFAULT
MAPSPEED_DEFAULT
> END STRING

> BEGIN STRING
標準イベントスピード

> END STRING

> BEGIN STRING
BATTLE_LOGSPEED_DEFAULT
BATTLE_LOGSPEED_DEFAULT
> END STRING

> BEGIN STRING
標準戦闘ログスピード

> END STRING

> BEGIN STRING
BATTLE_ANIMATIONSPEED_DEFAULT
BATTLE_ANIMATIONSPEED_DEFAULT
> END STRING

> BEGIN STRING
標準戦闘アニメーションスピード

> END STRING

> BEGIN STRING
標準戦闘敵スプライトスピード

> END STRING

> BEGIN STRING
BATTLE_MOTIONSPEED_DEFAULT
BATTLE_MOTIONSPEED_DEFAULT
> END STRING

> BEGIN STRING
標準戦闘武器モーションスピード

> END STRING

> BEGIN STRING
BATTLE_MOVESPEED_DEFAULT
BATTLE_MOVESPEED_DEFAULT
> END STRING

> BEGIN STRING
標準戦闘移動スピード

> END STRING

> BEGIN STRING
RAPID_MAPSPEED_DEFAULT
RAPID_MAPSPEED_DEFAULT
> END STRING

> BEGIN STRING
早送りイベントスピード

> END STRING

> BEGIN STRING
RAPID_BATTLE_LOGSPEED_DEFAULT
RAPID_BATTLE_LOGSPEED_DEFAULT
> END STRING

> BEGIN STRING
早送り戦闘ログスピード

> END STRING

> BEGIN STRING
RAPID_BATTLE_ANIMATIONSPEED_DEFAULT
RAPID_BATTLE_ANIMATIONSPEED_DEFAULT
> END STRING

> BEGIN STRING
早送り戦闘アニメーションスピード

> END STRING

> BEGIN STRING
早送り戦闘敵スプライトスピード

> END STRING

> BEGIN STRING
RAPID_BATTLE_MOTIONSPEED_DEFAULT
RAPID_BATTLE_MOTIONSPEED_DEFAULT
> END STRING

> BEGIN STRING
早送り戦闘武器モーションスピード

> END STRING

> BEGIN STRING
RAPID_BATTLE_MOVESPEED_DEFAULT
RAPID_BATTLE_MOVESPEED_DEFAULT
> END STRING

> BEGIN STRING
早送り戦闘移動スピード

> END STRING

> BEGIN STRING
_SKIPSPEED_DEFAULT
_SKIPSPEED_DEFAULT
> END STRING

> BEGIN STRING
デフォルトスキップ倍数

> END STRING

> BEGIN STRING
VarNo_Rapid_BattleRate
VarNo_Rapid_BattleRate
> END STRING

> BEGIN STRING
可変戦闘早送り倍数を格納する変数番号

> END STRING

> BEGIN STRING
VarNo_Rapid_MapRate
VarNo_Rapid_MapRate
> END STRING

> BEGIN STRING
可変イベント早送り倍数を格納する変数番号

> END STRING

> BEGIN STRING
SwitchNo_isSkip
SwitchNo_isSkip
> END STRING

> BEGIN STRING
スキップ中かを格納するスイッチ番号

> END STRING

> BEGIN STRING
SwitchNo_isNoSkip
SwitchNo_isNoSkip
> END STRING

> BEGIN STRING
スキップ禁止中かを格納するスイッチ番号

> END STRING

> BEGIN STRING
VarNo_BattleSpeed
VarNo_BattleSpeed
> END STRING

> BEGIN STRING
可変ゲームスピードを格納する変数番号

> END STRING

> BEGIN STRING
VarNo_MessageWaitEscapeCharacterSpeed
VarNo_MessageWaitEscapeCharacterSpeed
> END STRING

> BEGIN STRING
可変メッセージウェイト制御文字スピードを格納する変数番号

> END STRING

> BEGIN STRING
VarNo_SkipRate
VarNo_SkipRate
> END STRING

> BEGIN STRING
可変スキップ倍数を格納する変数番号

> END STRING

> BEGIN STRING
SwitchNo_IsBattle
SwitchNo_IsBattle
> END STRING

> BEGIN STRING
戦闘中かを格納するスイッチ番号

> END STRING

> BEGIN STRING
SwitchNo_RandomEncount
SwitchNo_RandomEncount
> END STRING

> BEGIN STRING
ランダムエンカウント時にONになるスイッチ番号

> END STRING

> BEGIN STRING
SwitchNo_BattleWin
SwitchNo_BattleWin
> END STRING

> BEGIN STRING
戦闘勝利時にONになるスイッチ番号

> END STRING

> BEGIN STRING
SwitchNo_BattleEscape
SwitchNo_BattleEscape
> END STRING

> BEGIN STRING
戦闘逃走時にONになるスイッチ番号

> END STRING

> BEGIN STRING
SwitchNo_BattleLose
SwitchNo_BattleLose
> END STRING

> BEGIN STRING
戦闘全滅時にONになるスイッチ番号

> END STRING

> BEGIN STRING
VarNo_LastBattleTroopID
VarNo_LastBattleTroopID
> END STRING

> BEGIN STRING
最後に戦闘した敵グループIDを格納する変数番号

> END STRING

> BEGIN STRING
isRapid_MapButton_ok
isRapid_MapButton_ok
> END STRING

> BEGIN STRING
決定ボタンでイベント早送り可能か

> END STRING

> BEGIN STRING
isRapid_BattleButton_ok
isRapid_BattleButton_ok
> END STRING

> BEGIN STRING
決定ボタンで戦闘早送り可能か

> END STRING

> BEGIN STRING
isRapid_MapButton_cancel
isRapid_MapButton_cancel
> END STRING

> BEGIN STRING
キャンセルボタンでイベント早送り可能か

> END STRING

> BEGIN STRING
isRapid_BattleButton_cancel
isRapid_BattleButton_cancel
> END STRING

> BEGIN STRING
キャンセルボタンで戦闘早送り可能か

> END STRING

> BEGIN STRING
isRapid_MapButton_shift
isRapid_MapButton_shift
> END STRING

> BEGIN STRING
ダッシュボタンでイベント早送り可能か

> END STRING

> BEGIN STRING
isRapid_BattleButton_shift
isRapid_BattleButton_shift
> END STRING

> BEGIN STRING
ダッシュボタンで戦闘早送り可能か

> END STRING

> BEGIN STRING
isSkipButton_ok
isSkipButton_ok
> END STRING

> BEGIN STRING
決定ボタンでスキップ可能か

> END STRING

> BEGIN STRING
isSkipButton_cancel
isSkipButton_cancel
> END STRING

> BEGIN STRING
キャンセルボタンでスキップ可能か

> END STRING

> BEGIN STRING
isSkipButton_shift
isSkipButton_shift
> END STRING

> BEGIN STRING
ダッシュボタンでスキップ可能か

> END STRING

> BEGIN STRING
isSkip_OnMapEvent
isSkip_OnMapEvent
> END STRING

> BEGIN STRING
マップイベント中もスキップ可能か

> END STRING

> BEGIN STRING
isSkip_OnMapMoving
isSkip_OnMapMoving
> END STRING

> BEGIN STRING
マップ移動中もスキップ可能か

> END STRING

> BEGIN STRING
isSkip_OnMapNeutral
isSkip_OnMapNeutral
> END STRING

> BEGIN STRING
マップ無操作中もスキップ可能か

> END STRING

> BEGIN STRING
isSkip_OnBattle
isSkip_OnBattle
> END STRING

> BEGIN STRING
戦闘中もスキップ可能か

> END STRING

> BEGIN STRING
MaxHPLimit
MaxHPLimit
> END STRING

> BEGIN STRING
最大HPの限界値

> END STRING

> BEGIN STRING
MaxMPLimit
MaxMPLimit
> END STRING

> BEGIN STRING
最大MPの限界値

> END STRING

> BEGIN STRING
ATKetcLimit
ATKetcLimit
> END STRING

> BEGIN STRING
攻撃力などの限界値

> END STRING

> BEGIN STRING
SubstiutedChara_MaxHPPercent
SubstiutedChara_MaxHPPercent
> END STRING

> BEGIN STRING
かばわれる側の最大HP％0-100

> END STRING

> BEGIN STRING
SubstiutedChara_MaxMPPercent
SubstiutedChara_MaxMPPercent
> END STRING

> BEGIN STRING
かばわれる側の最大MP％0-100

> END STRING

> BEGIN STRING
SubstiutingChara_MinHPPercent
SubstiutingChara_MinHPPercent
> END STRING

> BEGIN STRING
かばう側の最小HP％0-100

> END STRING

> BEGIN STRING
SubstiutingChara_MinMPPercent
SubstiutingChara_MinMPPercent
> END STRING

> BEGIN STRING
かばう側の最小MP％0-100

> END STRING

> BEGIN STRING
SubstiutingRate
SubstiutingRate
> END STRING

> BEGIN STRING
身代わり率％0-100

> END STRING

> BEGIN STRING
VarNo_Migawari_Sareta_AcorID
VarNo_Migawari_Sareta_AcorID
> END STRING

> BEGIN STRING
最後にかばわれたアクターIDを格納する変数番号

> END STRING

> BEGIN STRING
VarNo_Migawari_Shita_AcorID
VarNo_Migawari_Shita_AcorID
> END STRING

> BEGIN STRING
最後にかばったアクターIDを格納する変数番号

> END STRING

> BEGIN STRING
VarNo_Migawari_Sareta_EnemyID
VarNo_Migawari_Sareta_EnemyID
> END STRING

> BEGIN STRING
最後にかばわれた敵キャラIDを格納する変数番号

> END STRING

> BEGIN STRING
VarNo_Migawari_Shita_EnemyID
VarNo_Migawari_Shita_EnemyID
> END STRING

> BEGIN STRING
最後にかばった敵キャラIDを格納する変数番号

> END STRING

> BEGIN STRING
CommonEventNo_Migawari_Success_Actor
CommonEventNo_Migawari_Success_Actor
> END STRING

> BEGIN STRING
味方の身代わり成功時に実行するコモンイベント番号

> END STRING

> BEGIN STRING
CommonEventNo_Migawari_Success_Enemy
CommonEventNo_Migawari_Success_Enemy
> END STRING

> BEGIN STRING
敵の身代わり成功時に実行するコモンイベント番号

> END STRING

> BEGIN STRING
Default_Wait_Period
Default_Wait_Period
> END STRING

> BEGIN STRING
「＼.」の待ちフレーム数

> END STRING

> BEGIN STRING
Default_Wait_Line
Default_Wait_Line
> END STRING

> BEGIN STRING
「＼|」の待ちフレーム数

> END STRING

> BEGIN STRING
SkipModeOnが禁止中: スキップモードを実行しようとしましたが、スキップ禁止中ですので、自動的にOFFになりました。

> END STRING

> BEGIN STRING
SkipModeOn: スキップモードがONになりました。

> END STRING

> BEGIN STRING
SkipModeOff: スキップモードがOFFになりました。

> END STRING

> BEGIN STRING
shift
shift
> END STRING

> BEGIN STRING
cancel
cancel
> END STRING

> BEGIN STRING
ok
ok
> END STRING

> BEGIN STRING
SKIPMODE_ON
SKIPMODE_ON
> END STRING

> BEGIN STRING
スキップモードON

> END STRING

> BEGIN STRING
SKIPMODE_OFF
SKIPMODE_OFF
> END STRING

> BEGIN STRING
スキップモードOFF

> END STRING

> BEGIN STRING
■this._waitCount：

> END STRING

> BEGIN STRING
 がnullかundefinedになってるから、 初期値に戻すよ。

> END STRING

> BEGIN STRING
■_reduceCount：

> END STRING

> BEGIN STRING
 がおかしいよ。 デフォルト

> END STRING

> BEGIN STRING
に戻すよ。

> END STRING

> BEGIN STRING
 が0未満です。0だと止まってしまうので、 0.2にします。

> END STRING

> BEGIN STRING
 がおかしいから、 

> END STRING

> BEGIN STRING
 引いてもNaNになるよ。 0に初期化します。

> END STRING

> BEGIN STRING
.
.
> END STRING

> BEGIN STRING
minRPG_CustomizeGameSpeed.js 「\\.」のウェイトフレーム数の変更: _WaitPeriodDef:

> END STRING

> BEGIN STRING
 → 変換後:

> END STRING

> BEGIN STRING
|
|
> END STRING

> BEGIN STRING
minRPG_CustomizeGameSpeed: パラメータ「戦闘中かを格納するスイッチ番号」に変な値が入ってます。: 

> END STRING

> BEGIN STRING
minRPG_CustomizeGameSpeed: パラメータ「ランダムエンカウント時にONになるスイッチ番号」に変な値が入っています。: 

> END STRING

> BEGIN STRING
minRPG_CustomizeGameSpeed: パラメータ「最後に戦闘した敵グループIDを格納する変数番号」に変な値が入っています。: 

> END STRING

> BEGIN STRING
イベント戦闘発生(敵グループID: 

> END STRING

> BEGIN STRING
)
)
> END STRING

> BEGIN STRING
エンカウント戦闘発生(敵グループID: 

> END STRING

> BEGIN STRING
)。 次のエンカウント: 

> END STRING

> BEGIN STRING
 歩)

> END STRING

> BEGIN STRING
minRPG_CustomizeGameSpeed: パラメータ「戦闘勝利時にONになるスイッチ番号」に変な値が入ってます。: 

> END STRING

> BEGIN STRING
minRPG_CustomizeGameSpeed: パラメータ「戦闘逃走時にONになるスイッチ番号」に変な値が入ってます。: 

> END STRING

> BEGIN STRING
minRPG_CustomizeGameSpeed: パラメータ「戦闘全滅時にONになるスイッチ番号」に変な値が入ってます。: 

> END STRING

> BEGIN STRING
身代わり条件の変更：


> END STRING

> BEGIN STRING
のHP％ 

> END STRING

> BEGIN STRING
 が 

> END STRING

> BEGIN STRING
％以下で、かつMP％ 

> END STRING

> BEGIN STRING
％以下です。

> END STRING

> BEGIN STRING
★かばう成功: 

> END STRING

> BEGIN STRING
％以上で、MP％ 

> END STRING

> BEGIN STRING
％以上で、かつ

> END STRING

> BEGIN STRING
％の確率を満たしたので、


> END STRING

> BEGIN STRING
が

> END STRING

> BEGIN STRING
をかばいました。

> END STRING

> BEGIN STRING
minRPG_CustomizeGameSpeed: パラメータ「身代わりされたアクターIDを格納する変数番号」に変な値が入っています。: 

> END STRING

> BEGIN STRING
minRPG_CustomizeGameSpeed: パラメータ「身代わりしたアクターIDを格納する変数番号」に変な値が入っています。: 

> END STRING

> BEGIN STRING
 → 味方身代わり成功時コモンイベント 

> END STRING

> BEGIN STRING
 を実行

> END STRING

> BEGIN STRING
minRPG_CustomizeGameSpeed: パラメータ「味方の身代わり成功時に実行するコモンイベント番号」に変な値が入っています。: 

> END STRING

> BEGIN STRING
minRPG_CustomizeGameSpeed: パラメータ「身代わりされた敵キャラIDを格納する変数番号」に変な値が入っています。: 

> END STRING

> BEGIN STRING
minRPG_CustomizeGameSpeed: パラメータ「身代わりした敵キャラIDを格納する変数番号」に変な値が入っています。: 

> END STRING

> BEGIN STRING
 → 敵身代わり成功時コモンイベント 

> END STRING

> BEGIN STRING
minRPG_CustomizeGameSpeed: パラメータ「敵の身代わり成功時に実行するコモンイベント番号」に変な値が入っています。: 

> END STRING
