Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
MKR_MapItemSlot
MKR_MapItemSlot
> END STRING

> BEGIN STRING


> END STRING

> BEGIN STRING
\\
\\
> END STRING

> BEGIN STRING
bool
bool
> END STRING

> BEGIN STRING
ON
ON
> END STRING

> BEGIN STRING
TRUE
TRUE
> END STRING

> BEGIN STRING
1
1
> END STRING

> BEGIN STRING
num
num
> END STRING

> BEGIN STRING
float
float
> END STRING

> BEGIN STRING
string
string
> END STRING

> BEGIN STRING
lower
lower
> END STRING

> BEGIN STRING
upper
upper
> END STRING

> BEGIN STRING
[CheckParam] 
[CheckParam] 
> END STRING

> BEGIN STRING
のタイプが不正です: 

> END STRING

> BEGIN STRING
SlotVisible
SlotVisible
> END STRING

> BEGIN STRING
Slot_Visible
Slot_Visible
> END STRING

> BEGIN STRING
SlotOpacityOffset
SlotOpacityOffset
> END STRING

> BEGIN STRING
Slot_Opacity_Offset
Slot_Opacity_Offset
> END STRING

> BEGIN STRING
SlotBackground
SlotBackground
> END STRING

> BEGIN STRING
Slot_Background
Slot_Background
> END STRING

> BEGIN STRING
SlotNumber
SlotNumber
> END STRING

> BEGIN STRING
Slot_Number
Slot_Number
> END STRING

> BEGIN STRING
SlotX
SlotX
> END STRING

> BEGIN STRING
Slot_X
Slot_X
> END STRING

> BEGIN STRING
center
center
> END STRING

> BEGIN STRING
SlotY
SlotY
> END STRING

> BEGIN STRING
Slot_Y
Slot_Y
> END STRING

> BEGIN STRING
bottom
bottom
> END STRING

> BEGIN STRING
SlotSetW
SlotSetW
> END STRING

> BEGIN STRING
Slot_Set_Weapon
Slot_Set_Weapon
> END STRING

> BEGIN STRING
SlotSetA
SlotSetA
> END STRING

> BEGIN STRING
Slot_Set_Armor
Slot_Set_Armor
> END STRING

> BEGIN STRING
SlotCursorVisible
SlotCursorVisible
> END STRING

> BEGIN STRING
Slot_Cursor_Visible
Slot_Cursor_Visible
> END STRING

> BEGIN STRING
MapSlotOpacity
MapSlotOpacity
> END STRING

> BEGIN STRING
Map_Slot_Opacity
Map_Slot_Opacity
> END STRING

> BEGIN STRING
SlotAddMode
SlotAddMode
> END STRING

> BEGIN STRING
Slot_Add_Mode
Slot_Add_Mode
> END STRING

> BEGIN STRING
ItemRemoveMode
ItemRemoveMode
> END STRING

> BEGIN STRING
Item_Remove_Mode
Item_Remove_Mode
> END STRING

> BEGIN STRING
ItemUseMode
ItemUseMode
> END STRING

> BEGIN STRING
Item_Use_Mode
Item_Use_Mode
> END STRING

> BEGIN STRING
ItemCountVisible
ItemCountVisible
> END STRING

> BEGIN STRING
Item_Count_Visible
Item_Count_Visible
> END STRING

> BEGIN STRING
MenuSlotMode
MenuSlotMode
> END STRING

> BEGIN STRING
Menu_Slot_Mode
Menu_Slot_Mode
> END STRING

> BEGIN STRING
コマンド有効状態で追加

> END STRING

> BEGIN STRING
MenuBackground
MenuBackground
> END STRING

> BEGIN STRING
Menu_Background
Menu_Background
> END STRING

> BEGIN STRING
MapBackgroundEnable
MapBackgroundEnable
> END STRING

> BEGIN STRING
Map_Background_Enable
Map_Background_Enable
> END STRING

> BEGIN STRING
MenuSlotName
MenuSlotName
> END STRING

> BEGIN STRING
Menu_Slot_Name
Menu_Slot_Name
> END STRING

> BEGIN STRING
アイテムスロット

> END STRING

> BEGIN STRING
SlotSetName
SlotSetName
> END STRING

> BEGIN STRING
Slot_Set_Name
Slot_Set_Name
> END STRING

> BEGIN STRING
登録

> END STRING

> BEGIN STRING
SlotRemoveName
SlotRemoveName
> END STRING

> BEGIN STRING
Slot_Remove_Name
Slot_Remove_Name
> END STRING

> BEGIN STRING
削除

> END STRING

> BEGIN STRING
SlotSetDesc
SlotSetDesc
> END STRING

> BEGIN STRING
Slot_Set_Desc
Slot_Set_Desc
> END STRING

> BEGIN STRING
アイテムを登録したいスロットを選択し、
登録するアイテムを選択してください。

> END STRING

> BEGIN STRING
SlotChangeDesc
SlotChangeDesc
> END STRING

> BEGIN STRING
Slot_Change_Desc
Slot_Change_Desc
> END STRING

> BEGIN STRING
移動元のスロットを選択し、
交換先のスロットを選択してください。

> END STRING

> BEGIN STRING
SlotRemoveDesc
SlotRemoveDesc
> END STRING

> BEGIN STRING
Slot_Remove_Desc
Slot_Remove_Desc
> END STRING

> BEGIN STRING
アイテムの登録を解除するスロットを選択してください。

> END STRING

> BEGIN STRING
MenuSlotOpacity
MenuSlotOpacity
> END STRING

> BEGIN STRING
Menu_Slot_Opacity
Menu_Slot_Opacity
> END STRING

> BEGIN STRING
CateSortType
CateSortType
> END STRING

> BEGIN STRING
Category_Sort_Type
Category_Sort_Type
> END STRING

> BEGIN STRING
MapSlotWindow
MapSlotWindow
> END STRING

> BEGIN STRING
SizeRate
SizeRate
> END STRING

> BEGIN STRING
Map_Slot_Window.Size_Rate
Map_Slot_Window.Size_Rate
> END STRING

> BEGIN STRING
Map_Slot_Window
Map_Slot_Window
> END STRING

> BEGIN STRING
Size_Rate
Size_Rate
> END STRING

> BEGIN STRING
Padding
Padding
> END STRING

> BEGIN STRING
Map_Slot_Window.Padding
Map_Slot_Window.Padding
> END STRING

> BEGIN STRING
Spacing
Spacing
> END STRING

> BEGIN STRING
Map_Slot_Window.Spacing
Map_Slot_Window.Spacing
> END STRING

> BEGIN STRING
MenuSlotWindow
MenuSlotWindow
> END STRING

> BEGIN STRING
Menu_Slot_Window.Size_Rate
Menu_Slot_Window.Size_Rate
> END STRING

> BEGIN STRING
Menu_Slot_Window
Menu_Slot_Window
> END STRING

> BEGIN STRING
Menu_Slot_Window.Padding
Menu_Slot_Window.Padding
> END STRING

> BEGIN STRING
Menu_Slot_Window.Spacing
Menu_Slot_Window.Spacing
> END STRING

> BEGIN STRING
KeyConfig
KeyConfig
> END STRING

> BEGIN STRING
ItemUseKey
ItemUseKey
> END STRING

> BEGIN STRING
Item_Use_Key
Item_Use_Key
> END STRING

> BEGIN STRING
Key
Key
> END STRING

> BEGIN STRING
control
control
> END STRING

> BEGIN STRING
Slot1Key
Slot1Key
> END STRING

> BEGIN STRING
Slot_1_Key
Slot_1_Key
> END STRING

> BEGIN STRING
Slot2Key
Slot2Key
> END STRING

> BEGIN STRING
Slot_2_Key
Slot_2_Key
> END STRING

> BEGIN STRING
2
2
> END STRING

> BEGIN STRING
Slot3Key
Slot3Key
> END STRING

> BEGIN STRING
Slot_3_Key
Slot_3_Key
> END STRING

> BEGIN STRING
3
3
> END STRING

> BEGIN STRING
Slot4Key
Slot4Key
> END STRING

> BEGIN STRING
Slot_4_Key
Slot_4_Key
> END STRING

> BEGIN STRING
4
4
> END STRING

> BEGIN STRING
Slot5Key
Slot5Key
> END STRING

> BEGIN STRING
Slot_5_Key
Slot_5_Key
> END STRING

> BEGIN STRING
5
5
> END STRING

> BEGIN STRING
Slot6Key
Slot6Key
> END STRING

> BEGIN STRING
Slot_6_Key
Slot_6_Key
> END STRING

> BEGIN STRING
6
6
> END STRING

> BEGIN STRING
Slot7Key
Slot7Key
> END STRING

> BEGIN STRING
Slot_7_Key
Slot_7_Key
> END STRING

> BEGIN STRING
7
7
> END STRING

> BEGIN STRING
Slot8Key
Slot8Key
> END STRING

> BEGIN STRING
Slot_8_Key
Slot_8_Key
> END STRING

> BEGIN STRING
8
8
> END STRING

> BEGIN STRING
Slot9Key
Slot9Key
> END STRING

> BEGIN STRING
Slot_9_Key
Slot_9_Key
> END STRING

> BEGIN STRING
9
9
> END STRING

> BEGIN STRING
Slot10Key
Slot10Key
> END STRING

> BEGIN STRING
Slot_10_Key
Slot_10_Key
> END STRING

> BEGIN STRING
KeyboardMode
KeyboardMode
> END STRING

> BEGIN STRING
UseEnable
UseEnable
> END STRING

> BEGIN STRING
KeyboardMode.Use_Enable
KeyboardMode.Use_Enable
> END STRING

> BEGIN STRING
Keyboard_Mode
Keyboard_Mode
> END STRING

> BEGIN STRING
Use_Enable
Use_Enable
> END STRING

> BEGIN STRING
SelectEnable
SelectEnable
> END STRING

> BEGIN STRING
KeyboardMode.Select_Enable
KeyboardMode.Select_Enable
> END STRING

> BEGIN STRING
Select_Enable
Select_Enable
> END STRING

> BEGIN STRING
MouseMode
MouseMode
> END STRING

> BEGIN STRING
MouseMode.Use_Enable
MouseMode.Use_Enable
> END STRING

> BEGIN STRING
Mouse_Mode
Mouse_Mode
> END STRING

> BEGIN STRING
MouseMode.Select_Enable
MouseMode.Select_Enable
> END STRING

> BEGIN STRING
EventMode
EventMode
> END STRING

> BEGIN STRING
SlotEnable
SlotEnable
> END STRING

> BEGIN STRING
EventMode.Slot_Enable
EventMode.Slot_Enable
> END STRING

> BEGIN STRING
Event_Mode
Event_Mode
> END STRING

> BEGIN STRING
Slot_Enable
Slot_Enable
> END STRING

> BEGIN STRING
EventMode.Use_Enable
EventMode.Use_Enable
> END STRING

> BEGIN STRING
EventMode.Select_Enable
EventMode.Select_Enable
> END STRING

> BEGIN STRING
item
item
> END STRING

> BEGIN STRING
weapon
weapon
> END STRING

> BEGIN STRING
armor
armor
> END STRING

> BEGIN STRING
DEFAULT
DEFAULT
> END STRING

> BEGIN STRING
I_W_A
I_W_A
> END STRING

> BEGIN STRING
I_A_W
I_A_W
> END STRING

> BEGIN STRING
W_I_A
W_I_A
> END STRING

> BEGIN STRING
W_A_I
W_A_I
> END STRING

> BEGIN STRING
A_I_W
A_I_W
> END STRING

> BEGIN STRING
A_W_I
A_W_I
> END STRING

> BEGIN STRING
itemslot
itemslot
> END STRING

> BEGIN STRING
show
show
> END STRING

> BEGIN STRING
hide
hide
> END STRING

> BEGIN STRING
edit
edit
> END STRING

> BEGIN STRING
set
set
> END STRING

> BEGIN STRING
true
true
> END STRING

> BEGIN STRING
remove
remove
> END STRING

> BEGIN STRING
clear
clear
> END STRING

> BEGIN STRING
menu
menu
> END STRING

> BEGIN STRING
use
use
> END STRING

> BEGIN STRING
select
select
> END STRING

> BEGIN STRING
noadd
noadd
> END STRING

> BEGIN STRING
x
x
> END STRING

> BEGIN STRING
y
y
> END STRING

> BEGIN STRING
right
right
> END STRING

> BEGIN STRING
IconSet
IconSet
> END STRING

> BEGIN STRING
left
left
> END STRING

> BEGIN STRING
top
top
> END STRING

> BEGIN STRING
E
E
> END STRING

> BEGIN STRING



> END STRING

> BEGIN STRING
slotset
slotset
> END STRING

> BEGIN STRING
slotremove
slotremove
> END STRING

> BEGIN STRING
slotchange
slotchange
> END STRING

> BEGIN STRING
ok
ok
> END STRING

> BEGIN STRING
cancel
cancel
> END STRING

> BEGIN STRING
updateItemSlot WEAPON:%o
updateItemSlot WEAPON:%o
> END STRING

> BEGIN STRING
updateItemSlot ARMOR:%o
updateItemSlot ARMOR:%o
> END STRING

> BEGIN STRING
f
f
> END STRING

> BEGIN STRING
space
space
> END STRING
