Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
MKR_PlayerSensor
MKR_PlayerSensor
> END STRING

> BEGIN STRING


> END STRING

> BEGIN STRING
\\
\\
> END STRING

> BEGIN STRING
bool
bool
> END STRING

> BEGIN STRING
ON
ON
> END STRING

> BEGIN STRING
TRUE
TRUE
> END STRING

> BEGIN STRING
1
1
> END STRING

> BEGIN STRING
num
num
> END STRING

> BEGIN STRING
float
float
> END STRING

> BEGIN STRING
string
string
> END STRING

> BEGIN STRING
switch
switch
> END STRING

> BEGIN STRING
Lost_Sensor_Switch
Lost_Sensor_Switch
> END STRING

> BEGIN STRING
Plugin parameter value is not switch : 
Plugin parameter value is not switch : 
> END STRING

> BEGIN STRING
 : 
 : 
> END STRING

> BEGIN STRING
[CheckParam] 
[CheckParam] 
> END STRING

> BEGIN STRING
のタイプが不正です: 

> END STRING

> BEGIN STRING
[CEC] Plugin parameter type is illegal: 
[CEC] Plugin parameter type is illegal: 
> END STRING

> BEGIN STRING
true
true
> END STRING

> BEGIN STRING
Sensor_Switch
Sensor_Switch
> END STRING

> BEGIN STRING
D
D
> END STRING

> BEGIN STRING
Both_Sensor
Both_Sensor
> END STRING

> BEGIN STRING
Range_Visible
Range_Visible
> END STRING

> BEGIN STRING
Terrain_Decision
Terrain_Decision
> END STRING

> BEGIN STRING
Range_Color
Range_Color
> END STRING

> BEGIN STRING
white
white
> END STRING

> BEGIN STRING
Range_Opacity
Range_Opacity
> END STRING

> BEGIN STRING
Range_Position
Range_Position
> END STRING

> BEGIN STRING
Auto_Sensor
Auto_Sensor
> END STRING

> BEGIN STRING
Event_Decision
Event_Decision
> END STRING

> BEGIN STRING
Region_Decision
Region_Decision
> END STRING

> BEGIN STRING
Real_Range_X
Real_Range_X
> END STRING

> BEGIN STRING
Real_Range_Y
Real_Range_Y
> END STRING

> BEGIN STRING
Player_Found.Ballon
Player_Found.Ballon
> END STRING

> BEGIN STRING
Player_Found
Player_Found
> END STRING

> BEGIN STRING
Ballon
Ballon
> END STRING

> BEGIN STRING
Player_Found.Common_Event
Player_Found.Common_Event
> END STRING

> BEGIN STRING
Common_Event
Common_Event
> END STRING

> BEGIN STRING
Player_Found.Delay
Player_Found.Delay
> END STRING

> BEGIN STRING
Delay
Delay
> END STRING

> BEGIN STRING
name
name
> END STRING

> BEGIN STRING
Player_Found.Se.Name
Player_Found.Se.Name
> END STRING

> BEGIN STRING
Se
Se
> END STRING

> BEGIN STRING
Name
Name
> END STRING

> BEGIN STRING
volume
volume
> END STRING

> BEGIN STRING
Player_Found.Se.Volume
Player_Found.Se.Volume
> END STRING

> BEGIN STRING
Volume
Volume
> END STRING

> BEGIN STRING
pitch
pitch
> END STRING

> BEGIN STRING
Player_Found.Se.Pitch
Player_Found.Se.Pitch
> END STRING

> BEGIN STRING
Pitch
Pitch
> END STRING

> BEGIN STRING
pan
pan
> END STRING

> BEGIN STRING
Player_Found.Se.Pan
Player_Found.Se.Pan
> END STRING

> BEGIN STRING
Pan
Pan
> END STRING

> BEGIN STRING
Player_Lost.Ballon
Player_Lost.Ballon
> END STRING

> BEGIN STRING
Player_Lost
Player_Lost
> END STRING

> BEGIN STRING
Player_Lost.Common_Event
Player_Lost.Common_Event
> END STRING

> BEGIN STRING
Player_Lost.Delay
Player_Lost.Delay
> END STRING

> BEGIN STRING
Player_Lost.Se.Name
Player_Lost.Se.Name
> END STRING

> BEGIN STRING
Player_Lost.Se.Volume
Player_Lost.Se.Volume
> END STRING

> BEGIN STRING
Player_Lost.Se.Pitch
Player_Lost.Se.Pitch
> END STRING

> BEGIN STRING
Player_Lost.Se.Pan
Player_Lost.Se.Pan
> END STRING

> BEGIN STRING
Tracking_Priority
Tracking_Priority
> END STRING

> BEGIN STRING
Location_Reset
Location_Reset
> END STRING

> BEGIN STRING
pss
pss
> END STRING

> BEGIN STRING
start
start
> END STRING

> BEGIN STRING
force_start
force_start
> END STRING

> BEGIN STRING
stop
stop
> END STRING

> BEGIN STRING
reset
reset
> END STRING

> BEGIN STRING
lost
lost
> END STRING

> BEGIN STRING
t_start
t_start
> END STRING

> BEGIN STRING
t_stop
t_stop
> END STRING

> BEGIN STRING
t_reset
t_reset
> END STRING

> BEGIN STRING
t_move
t_move
> END STRING

> BEGIN STRING
t_lost
t_lost
> END STRING

> BEGIN STRING
code
code
> END STRING

> BEGIN STRING
parameters
parameters
> END STRING

> BEGIN STRING
route
route
> END STRING

> BEGIN STRING
list
list
> END STRING

> BEGIN STRING
repeat
repeat
> END STRING

> BEGIN STRING
skippable
skippable
> END STRING

> BEGIN STRING
wait
wait
> END STRING

> BEGIN STRING
df
df
> END STRING

> BEGIN STRING
u
u
> END STRING

> BEGIN STRING
r
r
> END STRING

> BEGIN STRING
l
l
> END STRING

> BEGIN STRING
d
d
> END STRING

> BEGIN STRING
!
!
> END STRING

> BEGIN STRING
f
f
> END STRING

> BEGIN STRING
s
s
> END STRING

> BEGIN STRING
 
 
> END STRING

> BEGIN STRING
C
C
> END STRING

> BEGIN STRING
Add
Add
> END STRING

> BEGIN STRING
Last
Last
> END STRING

> BEGIN STRING
Line
Line
> END STRING

> BEGIN STRING
Nopass
Nopass
> END STRING

> BEGIN STRING
_
_
> END STRING
