Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
MpiTitleMovie
MpiTitleMovie
> END STRING

> BEGIN STRING
Movie File Name
Movie File Name
> END STRING

> BEGIN STRING
Extension
Extension
> END STRING

> BEGIN STRING
X-coord
X-coord
> END STRING

> BEGIN STRING
Y-coord
Y-coord
> END STRING

> BEGIN STRING
Priority
Priority
> END STRING

> BEGIN STRING
auto
auto
> END STRING

> BEGIN STRING
./movies/
./movies/
> END STRING

> BEGIN STRING
added
added
> END STRING

> BEGIN STRING
removed
removed
> END STRING

> BEGIN STRING
video
video
> END STRING

> BEGIN STRING
loadeddata
loadeddata
> END STRING

> BEGIN STRING
ended
ended
> END STRING
