Autogenerated TRANS obj
> BEGIN STRING
MPP_ChoiceEX
MPP_ChoiceEX
> END STRING

> BEGIN STRING
maxPageRow
maxPageRow
> END STRING

> BEGIN STRING
Disabled Index
Disabled Index
> END STRING

> BEGIN STRING
Plugin Commands
Plugin Commands
> END STRING

> BEGIN STRING
Event Comment
Event Comment
> END STRING

> BEGIN STRING
top
top
> END STRING

> BEGIN STRING
選択肢ヘルプ

> END STRING

> BEGIN STRING
条件エラー 

 


 
> END STRING

> BEGIN STRING
ChoicePos
ChoicePos
> END STRING

> BEGIN STRING
ChoiceVariableId
ChoiceVariableId
> END STRING

> BEGIN STRING
ChoiceRect
ChoiceRect
> END STRING

> BEGIN STRING
ChoiceUnderMessage
ChoiceUnderMessage
> END STRING

> BEGIN STRING
close
close
> END STRING

> BEGIN STRING
select
select
> END STRING

> BEGIN STRING
choice
choice
> END STRING

> BEGIN STRING
processCancel
processCancel
> END STRING

> BEGIN STRING
processNewLine
processNewLine
> END STRING
