Autogenerated TRANS obj
> BEGIN STRING
MPP_MoveRouteEX
MPP_MoveRouteEX
> END STRING

> BEGIN STRING
Search Limit
Search Limit
> END STRING

> BEGIN STRING
this.movePos(
this.movePos(
> END STRING

> BEGIN STRING
this.moveX(
this.moveX(
> END STRING

> BEGIN STRING
)
)
> END STRING

> BEGIN STRING
this.moveY(
this.moveY(
> END STRING

> BEGIN STRING
this._x = Math.round(this._x)
this._x = Math.round(this._x)
> END STRING

> BEGIN STRING
this._y = Math.round(this._y)
this._y = Math.round(this._y)
> END STRING

> BEGIN STRING
WaitRoute
WaitRoute
> END STRING

> BEGIN STRING
route
route
> END STRING
