Autogenerated TRANS obj
> BEGIN STRING
MPP_MapLight
MPP_MapLight
> END STRING

> BEGIN STRING
,
,
> END STRING

> BEGIN STRING
Light Colors
Light Colors
> END STRING

> BEGIN STRING
Light Level 1 Regions
Light Level 1 Regions
> END STRING

> BEGIN STRING
Light Level 2 Regions
Light Level 2 Regions
> END STRING

> BEGIN STRING
Light Level 3 Regions
Light Level 3 Regions
> END STRING

> BEGIN STRING
Light Level 4 Regions
Light Level 4 Regions
> END STRING

> BEGIN STRING
Light Level 5 Regions
Light Level 5 Regions
> END STRING

> BEGIN STRING
Light Level 6 Regions
Light Level 6 Regions
> END STRING

> BEGIN STRING
Light Level 7 Regions
Light Level 7 Regions
> END STRING

> BEGIN STRING
Plugin Commands
Plugin Commands
> END STRING

> BEGIN STRING
Map Metadata
Map Metadata
> END STRING

> BEGIN STRING
Event Comments
Event Comments
> END STRING

> BEGIN STRING
lighter
lighter
> END STRING

> BEGIN STRING
rgba(%1,1)
rgba(%1,1)
> END STRING

> BEGIN STRING
rgba(%1,0)
rgba(%1,0)
> END STRING

> BEGIN STRING
black
black
> END STRING

> BEGIN STRING
Darkness
Darkness
> END STRING

> BEGIN STRING
MapLight
MapLight
> END STRING

> BEGIN STRING
 
 
> END STRING

> BEGIN STRING
SetCharLight
SetCharLight
> END STRING

> BEGIN STRING
255
255
> END STRING

> BEGIN STRING
ShowMapLight
ShowMapLight
> END STRING

> BEGIN STRING
MoveMapLight
MoveMapLight
> END STRING

> BEGIN STRING
EraseMapLight
EraseMapLight
> END STRING

> BEGIN STRING
SetMapDarkness
SetMapDarkness
> END STRING
