Autogenerated TRANS obj
> BEGIN STRING
MPP_EquipStatusEX
MPP_EquipStatusEX
> END STRING

> BEGIN STRING
,
,
> END STRING

> BEGIN STRING
Status Window Row
Status Window Row
> END STRING

> BEGIN STRING
Gauge Height
Gauge Height
> END STRING

> BEGIN STRING
rgb(%1)
rgb(%1)
> END STRING

> BEGIN STRING
Gauge Color
Gauge Color
> END STRING

> BEGIN STRING
224,255,255
224,255,255
> END STRING

> BEGIN STRING
Gauge Type
Gauge Type
> END STRING

> BEGIN STRING
Gauge Slope
Gauge Slope
> END STRING

> BEGIN STRING
param Gauge Max
param Gauge Max
> END STRING

> BEGIN STRING
{}
{}
> END STRING

> BEGIN STRING
Max Square
Max Square
> END STRING

> BEGIN STRING
xparam Gauge Max
xparam Gauge Max
> END STRING

> BEGIN STRING
sparam Gauge Max
sparam Gauge Max
> END STRING

> BEGIN STRING
rate Gauge Max
rate Gauge Max
> END STRING

> BEGIN STRING
Default Status
Default Status
> END STRING

> BEGIN STRING
Fixing Status
Fixing Status
> END STRING

> BEGIN STRING
Item Status
Item Status
> END STRING

> BEGIN STRING
Flow Status
Flow Status
> END STRING

> BEGIN STRING
Element Rate Params
Element Rate Params
> END STRING

> BEGIN STRING
Draw Ids
Draw Ids
> END STRING

> BEGIN STRING
Reverse?
Reverse?
> END STRING

> BEGIN STRING
View Type
View Type
> END STRING

> BEGIN STRING
Debuff Rate Params
Debuff Rate Params
> END STRING

> BEGIN STRING
Draw Params
Draw Params
> END STRING

> BEGIN STRING
State Rate Params
State Rate Params
> END STRING

> BEGIN STRING
State Resist Params
State Resist Params
> END STRING

> BEGIN STRING
Original Trait Type
Original Trait Type
> END STRING

> BEGIN STRING
xparams
xparams
> END STRING

> BEGIN STRING
sparams
sparams
> END STRING

> BEGIN STRING
Element Rate
Element Rate
> END STRING

> BEGIN STRING
Debuff Rate
Debuff Rate
> END STRING

> BEGIN STRING
State Rate
State Rate
> END STRING

> BEGIN STRING
State Resist
State Resist
> END STRING

> BEGIN STRING
Equip Metadata
Equip Metadata
> END STRING

> BEGIN STRING
mppEqSt
mppEqSt
> END STRING

> BEGIN STRING
update
update
> END STRING

> BEGIN STRING
param
param
> END STRING

> BEGIN STRING
elementRate
elementRate
> END STRING

> BEGIN STRING
debuffRate
debuffRate
> END STRING

> BEGIN STRING
stateRate
stateRate
> END STRING

> BEGIN STRING
isStateResist
isStateResist
> END STRING

> BEGIN STRING
stateResist
stateResist
> END STRING

> BEGIN STRING
original
original
> END STRING

> BEGIN STRING
black
black
> END STRING

> BEGIN STRING
transparent
transparent
> END STRING

> BEGIN STRING
round
round
> END STRING

> BEGIN STRING
right
right
> END STRING

> BEGIN STRING
+
+
> END STRING

> BEGIN STRING
-
-
> END STRING
