Autogenerated TRANS obj
> BEGIN STRING
PD_Transition
PD_Transition
> END STRING

> BEGIN STRING
Duration
Duration
> END STRING

> BEGIN STRING
Transition
Transition
> END STRING

> BEGIN STRING
set
set
> END STRING

> BEGIN STRING
clear
clear
> END STRING

> BEGIN STRING
duration
duration
> END STRING

> BEGIN STRING
トランジション

> END STRING

> BEGIN STRING
設定

> END STRING

> BEGIN STRING
解除

> END STRING

> BEGIN STRING
時間設定

> END STRING

> BEGIN STRING
none
none
> END STRING

> BEGIN STRING
無し

> END STRING

> BEGIN STRING
なし

> END STRING

> BEGIN STRING
rgb(128, 128, 128)
rgb(128, 128, 128)
> END STRING

> BEGIN STRING
rgb(255, 255, 255)
rgb(255, 255, 255)
> END STRING

> BEGIN STRING
rgb(0, 0, 0)
rgb(0, 0, 0)
> END STRING

> BEGIN STRING
rgba(255, 255, 255, 0)
rgba(255, 255, 255, 0)
> END STRING

> BEGIN STRING
rgba(0, 0, 0, 0)
rgba(0, 0, 0, 0)
> END STRING

> BEGIN STRING
img/transitions/
img/transitions/
> END STRING
