Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
null
null
> END STRING

> BEGIN STRING
"
"
> END STRING

> BEGIN STRING
PlayerDirectionControl
PlayerDirectionControl
> END STRING

> BEGIN STRING
CTRL_PLAYER_DIRECTION
CTRL_PLAYER_DIRECTION
> END STRING

> BEGIN STRING
execControlPlayerDirection
execControlPlayerDirection
> END STRING
