Autogenerated TRANS obj
> BEGIN STRING
RandomEventSet
RandomEventSet
> END STRING

> BEGIN STRING
RandomSetSwitchID
RandomSetSwitchID
> END STRING

> BEGIN STRING
RegionSetSwitchID
RegionSetSwitchID
> END STRING

> BEGIN STRING
InitTransfer
InitTransfer
> END STRING

> BEGIN STRING
RandomSetKey
RandomSetKey
> END STRING

> BEGIN STRING
<ランダム配置\>

> END STRING

> BEGIN STRING
RegionSetKey
RegionSetKey
> END STRING

> BEGIN STRING
<ランダムリージョン:(\\d+)\>

> END STRING

> BEGIN STRING
RandomSet
RandomSet
> END STRING

> BEGIN STRING
RegionSet
RegionSet
> END STRING

> BEGIN STRING
This is a static class
This is a static class
> END STRING
