Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
Ricon_BattleTransition
Ricon_BattleTransition
> END STRING

> BEGIN STRING
ON
ON
> END STRING

> BEGIN STRING
TRUE
TRUE
> END STRING

> BEGIN STRING
Speed
Speed
> END STRING

> BEGIN STRING
Zoom
Zoom
> END STRING

> BEGIN STRING
ZoomMode
ZoomMode
> END STRING

> BEGIN STRING
Flash
Flash
> END STRING

> BEGIN STRING
FlashRed
FlashRed
> END STRING

> BEGIN STRING
FlashGreen
FlashGreen
> END STRING

> BEGIN STRING
FlashBlue
FlashBlue
> END STRING

> BEGIN STRING
FlashIntensity
FlashIntensity
> END STRING

> BEGIN STRING
default
default
> END STRING

> BEGIN STRING
speed
speed
> END STRING

> BEGIN STRING
zoom
zoom
> END STRING

> BEGIN STRING
zoommode
zoommode
> END STRING

> BEGIN STRING
flash
flash
> END STRING

> BEGIN STRING
flashr
flashr
> END STRING

> BEGIN STRING
flashg
flashg
> END STRING

> BEGIN STRING
flashb
flashb
> END STRING

> BEGIN STRING
flashi
flashi
> END STRING

> BEGIN STRING
on
on
> END STRING

> BEGIN STRING
BattleTransition
BattleTransition
> END STRING

> BEGIN STRING
boolean
boolean
> END STRING

> BEGIN STRING
string
string
> END STRING

> BEGIN STRING
in
in
> END STRING

> BEGIN STRING
out
out
> END STRING

> BEGIN STRING
number
number
> END STRING
