Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
SE
SE
> END STRING

> BEGIN STRING
敵味方

> END STRING

> BEGIN STRING
EnemiesAndAllies
EnemiesAndAllies
> END STRING

> BEGIN STRING
使用者追加

> END STRING

> BEGIN STRING
AdditionUser
AdditionUser
> END STRING

> BEGIN STRING
使用者除外

> END STRING

> BEGIN STRING
RemoveUser
RemoveUser
> END STRING

> BEGIN STRING
使用者削除

> END STRING

> BEGIN STRING
重複除外

> END STRING

> BEGIN STRING
RemoveDuplication
RemoveDuplication
> END STRING

> BEGIN STRING
重複削除

> END STRING

> BEGIN STRING
ランダム

> END STRING

> BEGIN STRING
Random
Random
> END STRING

> BEGIN STRING
グループ

> END STRING

> BEGIN STRING
Group
Group
> END STRING

> BEGIN STRING
RandomNum
RandomNum
> END STRING

> BEGIN STRING
ランダム回数

> END STRING

> BEGIN STRING
Dead
Dead
> END STRING

> BEGIN STRING
戦闘不能
Incapable of combat
> END STRING
