Autogenerated TRANS obj
> BEGIN STRING
SimpleMsgSideView
SimpleMsgSideView
> END STRING

> BEGIN STRING
displayAttack
displayAttack
> END STRING

> BEGIN STRING
position
position
> END STRING

> BEGIN STRING
addItemNameText
addItemNameText
> END STRING

> BEGIN STRING
wait
wait
> END STRING

> BEGIN STRING
center
center
> END STRING
