Autogenerated TRANS obj
> BEGIN STRING
SimpleFollowerControl
SimpleFollowerControl
> END STRING

> BEGIN STRING
Follower Collision
Follower Collision
> END STRING

> BEGIN STRING
MoveFollower
MoveFollower
> END STRING

> BEGIN STRING
StopFollowers
StopFollowers
> END STRING

> BEGIN STRING
BalloonFollower
BalloonFollower
> END STRING

> BEGIN STRING
balloon
balloon
> END STRING
