Autogenerated TRANS obj
> BEGIN STRING
SSEP_BattleSpeedUp_v2
SSEP_BattleSpeedUp_v2
> END STRING

> BEGIN STRING
BattleSpeed (Default)
BattleSpeed (Default)
> END STRING

> BEGIN STRING
BattleSpeed (Boost)
BattleSpeed (Boost)
> END STRING

> BEGIN STRING
OkayKeyBoost
OkayKeyBoost
> END STRING

> BEGIN STRING
VisibleSwitch
VisibleSwitch
> END STRING

> BEGIN STRING
BoostToggleSwitch
BoostToggleSwitch
> END STRING

> BEGIN STRING
StateIcon
StateIcon
> END STRING

> BEGIN STRING
StateOverlay
StateOverlay
> END STRING

> BEGIN STRING
Weapon
Weapon
> END STRING

> BEGIN STRING
Balloon
Balloon
> END STRING

> BEGIN STRING
Motion
Motion
> END STRING

> BEGIN STRING
Damage
Damage
> END STRING

> BEGIN STRING
DamageMin
DamageMin
> END STRING

> BEGIN STRING
LogAnime BaseDelay
LogAnime BaseDelay
> END STRING

> BEGIN STRING
LogAnime NextDelay
LogAnime NextDelay
> END STRING

> BEGIN STRING
LogWaitCount Default
LogWaitCount Default
> END STRING

> BEGIN STRING
LogWaitCount Boost
LogWaitCount Boost
> END STRING

> BEGIN STRING
SE BoostON
SE BoostON
> END STRING

> BEGIN STRING
SE BoostOFF
SE BoostOFF
> END STRING

> BEGIN STRING
SE Volume
SE Volume
> END STRING

> BEGIN STRING
SwitchImage
SwitchImage
> END STRING

> BEGIN STRING
SwitchX
SwitchX
> END STRING

> BEGIN STRING
SwitchY
SwitchY
> END STRING

> BEGIN STRING
SwitchWidth
SwitchWidth
> END STRING

> BEGIN STRING
SwitchHeight
SwitchHeight
> END STRING

> BEGIN STRING
SwitchTop
SwitchTop
> END STRING

> BEGIN STRING
SwitchLeft
SwitchLeft
> END STRING

> BEGIN STRING
SwitchAnimePattern
SwitchAnimePattern
> END STRING

> BEGIN STRING
SwitchAnimeSpeed
SwitchAnimeSpeed
> END STRING

> BEGIN STRING
YEP Battle MotionWait
YEP Battle MotionWait
> END STRING

> BEGIN STRING
YEP Victory Wait
YEP Victory Wait
> END STRING

> BEGIN STRING
YEP ATB BoostSwitch
YEP ATB BoostSwitch
> END STRING

> BEGIN STRING
ATB Speed(Default)
ATB Speed(Default)
> END STRING

> BEGIN STRING
ATB Speed(Boost)
ATB Speed(Boost)
> END STRING

> BEGIN STRING
true
true
> END STRING

> BEGIN STRING
ok
ok
> END STRING

> BEGIN STRING
function
function
> END STRING

> BEGIN STRING
atb
atb
> END STRING
