Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
StartUpFullScreen
StartUpFullScreen
> END STRING

> BEGIN STRING
Shutdown
Shutdown
> END STRING

> BEGIN STRING
シャットダウン

> END STRING

> BEGIN STRING
フルスクリーンで起動

> END STRING

> BEGIN STRING
shutdown
shutdown
> END STRING

> BEGIN STRING
startUpFullScreen
startUpFullScreen
> END STRING
