Autogenerated TRANS obj
> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
TE
TE
> END STRING

> BEGIN STRING


> END STRING

> BEGIN STRING
\\
\\
> END STRING

> BEGIN STRING
固有イベント呼び出し

> END STRING

> BEGIN STRING
execCallOriginEvent
execCallOriginEvent
> END STRING

> BEGIN STRING
_CALL_ORIGIN_EVENT
_CALL_ORIGIN_EVENT
> END STRING

> BEGIN STRING
マップイベント呼び出し

> END STRING

> BEGIN STRING
execCallMapEvent
execCallMapEvent
> END STRING

> BEGIN STRING
_CALL_MAP_EVENT
_CALL_MAP_EVENT
> END STRING

> BEGIN STRING
セルフ変数の操作

> END STRING

> BEGIN STRING
execControlSelfVariable
execControlSelfVariable
> END STRING

> BEGIN STRING
_SET_SELF_VARIABLE
_SET_SELF_VARIABLE
> END STRING

> BEGIN STRING
セルフ変数の一括操作

> END STRING

> BEGIN STRING
execControlSelfVariableRange
execControlSelfVariableRange
> END STRING

> BEGIN STRING
_SET_RANGE_SELF_VARIABLE
_SET_RANGE_SELF_VARIABLE
> END STRING

> BEGIN STRING
null
null
> END STRING

> BEGIN STRING
"
"
> END STRING

> BEGIN STRING
TemplateEvent
TemplateEvent
> END STRING

> BEGIN STRING
name
name
> END STRING

> BEGIN STRING
'
'
> END STRING

> BEGIN STRING
OverRide
OverRide
> END STRING

> BEGIN STRING
上書き

> END STRING

> BEGIN STRING
getTemplateId
getTemplateId
> END STRING

> BEGIN STRING
getTemplateName
getTemplateName
> END STRING

> BEGIN STRING
SAN_MapGenerator
SAN_MapGenerator
> END STRING
