Autogenerated TRANS obj
> BEGIN STRING
TinyGetInfoWnd
TinyGetInfoWnd
> END STRING

> BEGIN STRING
Event Command Switch
Event Command Switch
> END STRING

> BEGIN STRING
Y position type
Y position type
> END STRING

> BEGIN STRING
Display Loss
Display Loss
> END STRING

> BEGIN STRING
Display at Battle
Display at Battle
> END STRING

> BEGIN STRING
wordMoney
wordMoney
> END STRING

> BEGIN STRING
money
money
> END STRING

> BEGIN STRING
iconMoney
iconMoney
> END STRING

> BEGIN STRING
textGainItem
textGainItem
> END STRING

> BEGIN STRING
You got %1
You got %1
> END STRING

> BEGIN STRING
textLoseItem
textLoseItem
> END STRING

> BEGIN STRING
You lost %1
You lost %1
> END STRING

> BEGIN STRING
Item SE filename
Item SE filename
> END STRING

> BEGIN STRING
Evasion1
Evasion1
> END STRING

> BEGIN STRING
Item SE volume
Item SE volume
> END STRING

> BEGIN STRING
Item SE pitch
Item SE pitch
> END STRING

> BEGIN STRING
Weapon SE filename
Weapon SE filename
> END STRING

> BEGIN STRING
Equip1
Equip1
> END STRING

> BEGIN STRING
Weapon SE volume
Weapon SE volume
> END STRING

> BEGIN STRING
Weapon SE pitch
Weapon SE pitch
> END STRING

> BEGIN STRING
Armor SE filename
Armor SE filename
> END STRING

> BEGIN STRING
Evasion2
Evasion2
> END STRING

> BEGIN STRING
Armor SE volume
Armor SE volume
> END STRING

> BEGIN STRING
Armor SE pitch
Armor SE pitch
> END STRING

> BEGIN STRING
Money SE filename
Money SE filename
> END STRING

> BEGIN STRING
Coin
Coin
> END STRING

> BEGIN STRING
Money SE volume
Money SE volume
> END STRING

> BEGIN STRING
Money SE pitch
Money SE pitch
> END STRING

> BEGIN STRING
item
item
> END STRING

> BEGIN STRING
gain
gain
> END STRING

> BEGIN STRING
lose
lose
> END STRING

> BEGIN STRING
weapon
weapon
> END STRING

> BEGIN STRING
armor
armor
> END STRING

> BEGIN STRING
\#000000
\#000000
> END STRING

> BEGIN STRING
×
×
> END STRING

> BEGIN STRING
center
center
> END STRING

> BEGIN STRING
right
right
> END STRING

> BEGIN STRING
left
left
> END STRING
