Autogenerated TRANS obj
> BEGIN STRING
TitleAnimation
TitleAnimation
> END STRING

> BEGIN STRING
name
name
> END STRING

> BEGIN STRING
pattern
pattern
> END STRING

> BEGIN STRING
x
x
> END STRING

> BEGIN STRING
y
y
> END STRING

> BEGIN STRING
wait
wait
> END STRING

> BEGIN STRING
loop
loop
> END STRING
