Autogenerated TRANS obj
> BEGIN STRING
TMBossHpGauge
TMBossHpGauge
> END STRING

> BEGIN STRING
gaugeWindowX
gaugeWindowX
> END STRING

> BEGIN STRING
gaugeWindowY
gaugeWindowY
> END STRING

> BEGIN STRING
gaugeWindowWidth
gaugeWindowWidth
> END STRING

> BEGIN STRING
gaugeWindowHeight
gaugeWindowHeight
> END STRING

> BEGIN STRING
gaugeColor
gaugeColor
> END STRING

> BEGIN STRING
\#e48040 \#f0c040
\#e48040 \#f0c040
> END STRING

> BEGIN STRING
 
 
> END STRING

> BEGIN STRING
gaugeValue
gaugeValue
> END STRING

> BEGIN STRING
true
true
> END STRING

> BEGIN STRING
bossName
bossName
> END STRING

> BEGIN STRING
shakeTime
shakeTime
> END STRING

> BEGIN STRING
windowOpacity
windowOpacity
> END STRING

> BEGIN STRING
collideOpacity
collideOpacity
> END STRING

> BEGIN STRING
messageBusyHide
messageBusyHide
> END STRING

> BEGIN STRING
eventBusyHide
eventBusyHide
> END STRING

> BEGIN STRING
setBossHpGauge
setBossHpGauge
> END STRING

> BEGIN STRING
startAutoBossHpGauge
startAutoBossHpGauge
> END STRING

> BEGIN STRING
stopAutoBossHpGauge
stopAutoBossHpGauge
> END STRING

> BEGIN STRING
hideBossHpGauge
hideBossHpGauge
> END STRING

> BEGIN STRING
showBossHpGauge
showBossHpGauge
> END STRING

> BEGIN STRING
CLEAR
CLEAR
> END STRING

> BEGIN STRING
SHAKE
SHAKE
> END STRING

> BEGIN STRING
right
right
> END STRING
