Autogenerated TRANS obj
> BEGIN STRING


> END STRING

> BEGIN STRING
\\
\\
> END STRING

> BEGIN STRING
 
 
> END STRING

> BEGIN STRING
changeEquipSlotEx
changeEquipSlotEx
> END STRING

> BEGIN STRING
forceChangeEquipSlotEx
forceChangeEquipSlotEx
> END STRING

> BEGIN STRING
clearEquipmentsSlotEx
clearEquipmentsSlotEx
> END STRING
