Autogenerated TRANS obj
> BEGIN STRING
TMEventItemEx
TMEventItemEx
> END STRING

> BEGIN STRING
helpWindowEnabledItem
helpWindowEnabledItem
> END STRING

> BEGIN STRING
1
1
> END STRING

> BEGIN STRING
helpWindowEnabledKey
helpWindowEnabledKey
> END STRING

> BEGIN STRING
helpWindowEnabledA
helpWindowEnabledA
> END STRING

> BEGIN STRING
helpWindowEnabledB
helpWindowEnabledB
> END STRING

> BEGIN STRING
showItemNumberItem
showItemNumberItem
> END STRING

> BEGIN STRING
showItemNumberKey
showItemNumberKey
> END STRING

> BEGIN STRING
showItemNumberA
showItemNumberA
> END STRING

> BEGIN STRING
showItemNumberB
showItemNumberB
> END STRING

> BEGIN STRING
numVisibleRowsItem
numVisibleRowsItem
> END STRING

> BEGIN STRING
numVisibleRowsKey
numVisibleRowsKey
> END STRING

> BEGIN STRING
numVisibleRowsA
numVisibleRowsA
> END STRING

> BEGIN STRING
numVisibleRowsB
numVisibleRowsB
> END STRING

> BEGIN STRING
fixPlacement
fixPlacement
> END STRING

> BEGIN STRING
setEventItemSubCategory
setEventItemSubCategory
> END STRING

> BEGIN STRING
top
top
> END STRING
