Autogenerated TRANS obj
> BEGIN STRING
TMGreedShop
TMGreedShop
> END STRING

> BEGIN STRING
materialWindowPosition
materialWindowPosition
> END STRING

> BEGIN STRING
materialWindowWidth
materialWindowWidth
> END STRING

> BEGIN STRING
buyWindowWidth
buyWindowWidth
> END STRING

> BEGIN STRING
buyWindowHeight
buyWindowHeight
> END STRING

> BEGIN STRING
materialMax
materialMax
> END STRING

> BEGIN STRING
fontRate
fontRate
> END STRING

> BEGIN STRING
greedCommand
greedCommand
> END STRING

> BEGIN STRING
購入する

> END STRING

> BEGIN STRING
needText
needText
> END STRING

> BEGIN STRING
showSellCommand
showSellCommand
> END STRING

> BEGIN STRING
true
true
> END STRING

> BEGIN STRING
showMaterialWindow
showMaterialWindow
> END STRING

> BEGIN STRING
overlaid
overlaid
> END STRING

> BEGIN STRING
backOpacity
backOpacity
> END STRING

> BEGIN STRING
showMaterialFromNumberWindow
showMaterialFromNumberWindow
> END STRING

> BEGIN STRING
showPrice
showPrice
> END STRING

> BEGIN STRING
seGreedBuy
seGreedBuy
> END STRING

> BEGIN STRING
{}
{}
> END STRING

> BEGIN STRING
mat
mat
> END STRING

> BEGIN STRING
I
I
> END STRING

> BEGIN STRING
W
W
> END STRING

> BEGIN STRING
A
A
> END STRING

> BEGIN STRING
greedShop
greedShop
> END STRING

> BEGIN STRING
center
center
> END STRING

> BEGIN STRING
/
/
> END STRING

> BEGIN STRING
--/
--/
> END STRING

> BEGIN STRING
   
   
> END STRING

> BEGIN STRING
right
right
> END STRING

> BEGIN STRING
IconSet
IconSet
> END STRING

> BEGIN STRING
buy
buy
> END STRING

> BEGIN STRING
sell
sell
> END STRING

> BEGIN STRING
cancel
cancel
> END STRING

> BEGIN STRING
 
 
> END STRING
