Autogenerated TRANS obj
> BEGIN STRING
TMMapHpGauge
TMMapHpGauge
> END STRING

> BEGIN STRING
gaugeWindowX
gaugeWindowX
> END STRING

> BEGIN STRING
gaugeWindowY
gaugeWindowY
> END STRING

> BEGIN STRING
gaugeWindowWidth
gaugeWindowWidth
> END STRING

> BEGIN STRING
gaugeWindowHeight
gaugeWindowHeight
> END STRING

> BEGIN STRING
A
A
> END STRING

> BEGIN STRING
B
B
> END STRING

> BEGIN STRING
C
C
> END STRING

> BEGIN STRING
D
D
> END STRING

> BEGIN STRING
gauge
gauge
> END STRING

> BEGIN STRING
 
 
> END STRING

> BEGIN STRING
faceOffsetX
faceOffsetX
> END STRING

> BEGIN STRING
faceOffsetY
faceOffsetY
> END STRING

> BEGIN STRING
stateIconMax
stateIconMax
> END STRING

> BEGIN STRING
stateIconX
stateIconX
> END STRING

> BEGIN STRING
stateIconY
stateIconY
> END STRING

> BEGIN STRING
goldWidth
goldWidth
> END STRING

> BEGIN STRING
goldX
goldX
> END STRING

> BEGIN STRING
goldY
goldY
> END STRING

> BEGIN STRING
vnMax
vnMax
> END STRING

> BEGIN STRING
false
false
> END STRING

> BEGIN STRING
shakeTime
shakeTime
> END STRING

> BEGIN STRING
collideOpacity
collideOpacity
> END STRING

> BEGIN STRING
startVisible
startVisible
> END STRING

> BEGIN STRING
true
true
> END STRING

> BEGIN STRING
windowOpacity
windowOpacity
> END STRING

> BEGIN STRING
messageBusyHide
messageBusyHide
> END STRING

> BEGIN STRING
eventBusyHide
eventBusyHide
> END STRING

> BEGIN STRING
useBattleScene
useBattleScene
> END STRING

> BEGIN STRING
gaugeWindowBattleX
gaugeWindowBattleX
> END STRING

> BEGIN STRING
gaugeWindowBattleY
gaugeWindowBattleY
> END STRING

> BEGIN STRING
showHpGauge
showHpGauge
> END STRING

> BEGIN STRING
hideHpGauge
hideHpGauge
> END STRING

> BEGIN STRING
moveHpGaugeWindow
moveHpGaugeWindow
> END STRING

> BEGIN STRING
SHAKE
SHAKE
> END STRING

> BEGIN STRING
HP
HP
> END STRING

> BEGIN STRING
MP
MP
> END STRING

> BEGIN STRING
TP
TP
> END STRING

> BEGIN STRING
LV
LV
> END STRING

> BEGIN STRING
VN
VN
> END STRING

> BEGIN STRING
-------
-------
> END STRING

> BEGIN STRING
right
right
> END STRING

> BEGIN STRING
/
/
> END STRING
