Autogenerated TRANS obj
> BEGIN STRING
TMSecondName
TMSecondName
> END STRING

> BEGIN STRING
secondNameCommand
secondNameCommand
> END STRING

> BEGIN STRING
defaultSecondNameId
defaultSecondNameId
> END STRING

> BEGIN STRING
vnSecondNameExp
vnSecondNameExp
> END STRING

> BEGIN STRING
dateFontSize
dateFontSize
> END STRING

> BEGIN STRING
equipText
equipText
> END STRING

> BEGIN STRING
infoWindowWidth
infoWindowWidth
> END STRING

> BEGIN STRING
infoWindowNumberText
infoWindowNumberText
> END STRING

> BEGIN STRING
infoWindowExpText
infoWindowExpText
> END STRING

> BEGIN STRING
hidePartyMember
hidePartyMember
> END STRING

> BEGIN STRING
false
false
> END STRING

> BEGIN STRING
/
/
> END STRING

> BEGIN STRING
 
 
> END STRING

> BEGIN STRING
gainSecondName
gainSecondName
> END STRING

> BEGIN STRING
hasSecondName
hasSecondName
> END STRING

> BEGIN STRING
secondName
secondName
> END STRING

> BEGIN STRING
right
right
> END STRING

> BEGIN STRING
ok
ok
> END STRING

> BEGIN STRING
cancel
cancel
> END STRING

> BEGIN STRING
pagedown
pagedown
> END STRING

> BEGIN STRING
pageup
pageup
> END STRING
