Autogenerated TRANS obj
> BEGIN STRING
TMShooting
TMShooting
> END STRING

> BEGIN STRING
holdType
holdType
> END STRING

> BEGIN STRING
SWITCH
SWITCH
> END STRING

> BEGIN STRING
deadSwitch
deadSwitch
> END STRING

> BEGIN STRING
A
A
> END STRING

> BEGIN STRING
resetDeadSwitch
resetDeadSwitch
> END STRING

> BEGIN STRING
1
1
> END STRING

> BEGIN STRING
bulletBlockTag
bulletBlockTag
> END STRING

> BEGIN STRING
bulletBlockRegion
bulletBlockRegion
> END STRING

> BEGIN STRING
defaultDeadAnimeId
defaultDeadAnimeId
> END STRING

> BEGIN STRING
levelUpAnimeId
levelUpAnimeId
> END STRING

> BEGIN STRING
leaderShotSeParam
leaderShotSeParam
> END STRING

> BEGIN STRING
{}
{}
> END STRING

> BEGIN STRING
leaderShotSe
leaderShotSe
> END STRING

> BEGIN STRING
playerDeadEventId
playerDeadEventId
> END STRING

> BEGIN STRING
invincibleFollower
invincibleFollower
> END STRING

> BEGIN STRING
useGameover
useGameover
> END STRING

> BEGIN STRING
maxPlayerBullet
maxPlayerBullet
> END STRING

> BEGIN STRING
maxEnemyBullet
maxEnemyBullet
> END STRING

> BEGIN STRING
equipDummyX
equipDummyX
> END STRING

> BEGIN STRING
equipDummyY
equipDummyY
> END STRING

> BEGIN STRING
useLevelUpMessage
useLevelUpMessage
> END STRING

> BEGIN STRING
use strict
use strict
> END STRING

> BEGIN STRING
shot
shot
> END STRING

> BEGIN STRING
hold
hold
> END STRING

> BEGIN STRING
bulletSizeTable
bulletSizeTable
> END STRING

> BEGIN STRING
,
,
> END STRING

> BEGIN STRING
bulletBlendTable
bulletBlendTable
> END STRING

> BEGIN STRING
message
message
> END STRING

> BEGIN STRING
shootingBullet
shootingBullet
> END STRING

> BEGIN STRING
3
3
> END STRING

> BEGIN STRING
GetInformation
GetInformation
> END STRING

> BEGIN STRING
startAutoShot
startAutoShot
> END STRING

> BEGIN STRING
stopAutoShot
stopAutoShot
> END STRING

> BEGIN STRING
nwayShot
nwayShot
> END STRING

> BEGIN STRING
nwayAim
nwayAim
> END STRING

> BEGIN STRING
nallShot
nallShot
> END STRING

> BEGIN STRING
nallAim
nallAim
> END STRING

> BEGIN STRING
stopPlayerShot
stopPlayerShot
> END STRING

> BEGIN STRING
startPlayerShot
startPlayerShot
> END STRING

> BEGIN STRING
stopEnemyShot
stopEnemyShot
> END STRING

> BEGIN STRING
startEnemyShot
startEnemyShot
> END STRING

> BEGIN STRING
deletePlayerBullets
deletePlayerBullets
> END STRING

> BEGIN STRING
deleteEnemyBullets
deleteEnemyBullets
> END STRING

> BEGIN STRING
forceShot
forceShot
> END STRING

> BEGIN STRING
bulletPause
bulletPause
> END STRING

> BEGIN STRING
off
off
> END STRING

> BEGIN STRING
setCollision
setCollision
> END STRING

> BEGIN STRING
setShiftFiringY
setShiftFiringY
> END STRING
