Autogenerated TRANS obj
> BEGIN STRING
YEP_MessageCore
YEP_MessageCore
> END STRING

> BEGIN STRING
Default Rows
Default Rows
> END STRING

> BEGIN STRING
Default Width
Default Width
> END STRING

> BEGIN STRING
Face Indent
Face Indent
> END STRING

> BEGIN STRING
Fast Forward
Fast Forward
> END STRING

> BEGIN STRING
Word Wrapping
Word Wrapping
> END STRING

> BEGIN STRING
Description Wrap
Description Wrap
> END STRING

> BEGIN STRING
Font Name
Font Name
> END STRING

> BEGIN STRING
Font Size
Font Size
> END STRING

> BEGIN STRING
Font Size Change
Font Size Change
> END STRING

> BEGIN STRING
Font Changed Max
Font Changed Max
> END STRING

> BEGIN STRING
Font Changed Min
Font Changed Min
> END STRING

> BEGIN STRING
Name Box Buffer X
Name Box Buffer X
> END STRING

> BEGIN STRING
Name Box Buffer Y
Name Box Buffer Y
> END STRING

> BEGIN STRING
Name Box Padding
Name Box Padding
> END STRING

> BEGIN STRING
Name Box Color
Name Box Color
> END STRING

> BEGIN STRING
Name Box Clear
Name Box Clear
> END STRING

> BEGIN STRING
Name Box Added Text
Name Box Added Text
> END STRING

> BEGIN STRING
Bold 
Bold 
> END STRING

> BEGIN STRING
px 
px 
> END STRING

> BEGIN STRING
<WordWrap\>
<WordWrap\>
> END STRING

> BEGIN STRING
MessageRows
MessageRows
> END STRING

> BEGIN STRING
MessageWidth
MessageWidth
> END STRING

> BEGIN STRING
EnableWordWrap
EnableWordWrap
> END STRING

> BEGIN STRING
DisableWordWrap
DisableWordWrap
> END STRING

> BEGIN STRING
message
message
> END STRING

> BEGIN STRING
rgba(0, 0, 0, 0.5)
rgba(0, 0, 0, 0.5)
> END STRING

> BEGIN STRING



> END STRING

> BEGIN STRING
I[
I[
> END STRING

> BEGIN STRING
]
]
> END STRING

> BEGIN STRING
FR
FR
> END STRING

> BEGIN STRING
FS
FS
> END STRING

> BEGIN STRING
FN
FN
> END STRING

> BEGIN STRING
FB
FB
> END STRING

> BEGIN STRING
FI
FI
> END STRING

> BEGIN STRING
OC
OC
> END STRING

> BEGIN STRING
OW
OW
> END STRING

> BEGIN STRING
PX
PX
> END STRING

> BEGIN STRING
PY
PY
> END STRING

> BEGIN STRING
 
 
> END STRING

> BEGIN STRING
!
!
> END STRING

> BEGIN STRING
W
W
> END STRING
