Autogenerated TRANS obj
> BEGIN STRING
YEP_EventChasePlayer
YEP_EventChasePlayer
> END STRING

> BEGIN STRING
Sight Lock
Sight Lock
> END STRING

> BEGIN STRING
See Player
See Player
> END STRING

> BEGIN STRING
Alert Timer
Alert Timer
> END STRING

> BEGIN STRING
Alert Balloon
Alert Balloon
> END STRING

> BEGIN STRING
Alert Sound
Alert Sound
> END STRING

> BEGIN STRING
Alert Common Event
Alert Common Event
> END STRING
